//File Automatically generated by SystemC Netlister Time
#include "pfm_dynamic_sci.h"
pfm_dynamic_sci::pfm_dynamic_sci(const sc_module_name& module_name) : xsc::utils::xsc_sim_conn_base(module_name) 
{
	//Exported sockets Instantiation
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("pfm_dynamic_sci","C0_DDR_MAXI_0_tlm_MODE",0,"pfm_dynamic_memory_subsystem_0","M01_AXI_tlm_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("pfm_dynamic_sci","C0_DDR_MAXI_0_tlm_MODE",0,"pfm_dynamic_memory_subsystem_0","M01_AXI_tlm_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("pfm_dynamic_sci","data_M_AXI_4_tlm_MODE",0,"pfm_dynamic_xtlm_simple_intercon_0_0","S04_AXI_TLM_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("pfm_dynamic_sci","data_M_AXI_4_tlm_MODE",0,"pfm_dynamic_xtlm_simple_intercon_0_0","S04_AXI_TLM_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("pfm_dynamic_sci","data_M_AXI_0_tlm_MODE",0,"pfm_dynamic_xtlm_simple_intercon_0_0","S00_AXI_TLM_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("pfm_dynamic_sci","data_M_AXI_0_tlm_MODE",0,"pfm_dynamic_xtlm_simple_intercon_0_0","S00_AXI_TLM_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("pfm_dynamic_sci","data_M_AXI_3_tlm_MODE",0,"pfm_dynamic_xtlm_simple_intercon_0_0","S03_AXI_TLM_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("pfm_dynamic_sci","data_M_AXI_3_tlm_MODE",0,"pfm_dynamic_xtlm_simple_intercon_0_0","S03_AXI_TLM_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("pfm_dynamic_sci","data_M_AXI_1_tlm_MODE",0,"pfm_dynamic_xtlm_simple_intercon_0_0","S01_AXI_TLM_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("pfm_dynamic_sci","data_M_AXI_1_tlm_MODE",0,"pfm_dynamic_xtlm_simple_intercon_0_0","S01_AXI_TLM_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("pfm_dynamic_sci","data_M_AXI_2_tlm_MODE",0,"pfm_dynamic_xtlm_simple_intercon_0_0","S02_AXI_TLM_MODE");
	
	xsc::utils::xsc_sim_manager::addAssociateInstanceParameter("pfm_dynamic_sci","data_M_AXI_2_tlm_MODE",0,"pfm_dynamic_xtlm_simple_intercon_0_0","S02_AXI_TLM_MODE");
	
	//Add TLM Parameters
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_dpa_mon0_0","TRACE_OUT_TLM_MODE","pfm_dynamic_dpa_hub_0","TRACE_IN_0_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_dpa_mon1_0","TRACE_OUT_0_TLM_MODE","pfm_dynamic_dpa_hub_0","TRACE_IN_1_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_dpa_mon1_0","TRACE_OUT_1_TLM_MODE","pfm_dynamic_dpa_hub_0","TRACE_IN_2_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_dpa_mon2_0","TRACE_OUT_TLM_MODE","pfm_dynamic_dpa_hub_0","TRACE_IN_3_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_dpa_mon3_0","TRACE_OUT_0_TLM_MODE","pfm_dynamic_dpa_hub_0","TRACE_IN_4_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_dpa_mon3_0","TRACE_OUT_1_TLM_MODE","pfm_dynamic_dpa_hub_0","TRACE_IN_5_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xtlm_simple_intercon_0_0","M00_AXI_TLM_MODE","pfm_dynamic_icn_pass_0_0","S00_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xtlm_simple_intercon_0_0","M00_AXI_TLM_MODE","pfm_dynamic_icn_pass_0_0","S00_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_icn_pass_0_0","M00_AXI_TLM_MODE","pfm_dynamic_memory_subsystem_0","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_icn_pass_0_0","M00_AXI_TLM_MODE","pfm_dynamic_memory_subsystem_0","S00_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_memory_subsystem_0","M00_AXI_tlm_MODE","pfm_dynamic_sim_ddr_0_0","C0_DDR_SAXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_memory_subsystem_0","M00_AXI_tlm_MODE","pfm_dynamic_sim_ddr_0_0","C0_DDR_SAXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xtlm_simple_intercon_0_0","M01_AXI_TLM_MODE","pfm_dynamic_icn_pass_1_0","S00_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xtlm_simple_intercon_0_0","M01_AXI_TLM_MODE","pfm_dynamic_icn_pass_1_0","S00_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_icn_pass_1_0","M00_AXI_TLM_MODE","pfm_dynamic_memory_subsystem_0","S01_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_icn_pass_1_0","M00_AXI_TLM_MODE","pfm_dynamic_memory_subsystem_0","S01_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xtlm_simple_intercon_0_0","M02_AXI_TLM_MODE","pfm_dynamic_icn_pass_2_0","S00_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xtlm_simple_intercon_0_0","M02_AXI_TLM_MODE","pfm_dynamic_icn_pass_2_0","S00_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_icn_pass_2_0","M00_AXI_TLM_MODE","pfm_dynamic_memory_subsystem_0","S02_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_icn_pass_2_0","M00_AXI_TLM_MODE","pfm_dynamic_memory_subsystem_0","S02_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_memory_subsystem_0","M02_AXI_tlm_MODE","pfm_dynamic_sim_ddr_2_0","C0_DDR_SAXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_memory_subsystem_0","M02_AXI_tlm_MODE","pfm_dynamic_sim_ddr_2_0","C0_DDR_SAXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xtlm_simple_intercon_0_0","M03_AXI_TLM_MODE","pfm_dynamic_icn_pass_3_0","S00_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xtlm_simple_intercon_0_0","M03_AXI_TLM_MODE","pfm_dynamic_icn_pass_3_0","S00_AXI_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_icn_pass_3_0","M00_AXI_TLM_MODE","pfm_dynamic_memory_subsystem_0","S03_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_icn_pass_3_0","M00_AXI_TLM_MODE","pfm_dynamic_memory_subsystem_0","S03_AXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_memory_subsystem_0","M03_AXI_tlm_MODE","pfm_dynamic_sim_ddr_3_0","C0_DDR_SAXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_memory_subsystem_0","M03_AXI_tlm_MODE","pfm_dynamic_sim_ddr_3_0","C0_DDR_SAXI_tlm_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xtlm_simple_intercon_0_0","M04_AXI_TLM_MODE","pfm_dynamic_dpa_hub_0","S_AXIMM_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceConnParameters("pfm_dynamic_xtlm_simple_intercon_0_0","M04_AXI_TLM_MODE","pfm_dynamic_dpa_hub_0","S_AXIMM_TLM_MODE",1);
	xsc::utils::xsc_sim_manager::addInstanceParameter("pfm_dynamic_sci","userpf_control_M_AXI_TLM_MODE",-1);
	
	xsc::utils::xsc_sim_manager::addInstance("pfm_dynamic_sci", this);
}
pfm_dynamic_sci::~pfm_dynamic_sci()
{
}
void pfm_dynamic_sci::initConnModule() {

	pfm_dynamic_memory_subsystem_0_sc*  inst0=dynamic_cast<pfm_dynamic_memory_subsystem_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_memory_subsystem_0"));
	registerTlmSocket("C0_DDR_MAXI_0_tlm_aximm_read_socket",inst0->M01_AXI_tlm_aximm_read_socket);
	pfm_dynamic_memory_subsystem_0_sc*  inst1=dynamic_cast<pfm_dynamic_memory_subsystem_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_memory_subsystem_0"));
	registerTlmSocket("C0_DDR_MAXI_0_tlm_aximm_write_socket",inst1->M01_AXI_tlm_aximm_write_socket);
	pfm_dynamic_xtlm_simple_intercon_0_0_sc*  inst2=dynamic_cast<pfm_dynamic_xtlm_simple_intercon_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xtlm_simple_intercon_0_0"));
	registerTlmSocket("data_M_AXI_4_tlm_aximm_read_socket",inst2->target_4_rd_socket);
	pfm_dynamic_xtlm_simple_intercon_0_0_sc*  inst3=dynamic_cast<pfm_dynamic_xtlm_simple_intercon_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xtlm_simple_intercon_0_0"));
	registerTlmSocket("data_M_AXI_4_tlm_aximm_write_socket",inst3->target_4_wr_socket);
	pfm_dynamic_xtlm_simple_intercon_0_0_sc*  inst4=dynamic_cast<pfm_dynamic_xtlm_simple_intercon_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xtlm_simple_intercon_0_0"));
	registerTlmSocket("data_M_AXI_0_tlm_aximm_read_socket",inst4->target_0_rd_socket);
	pfm_dynamic_xtlm_simple_intercon_0_0_sc*  inst5=dynamic_cast<pfm_dynamic_xtlm_simple_intercon_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xtlm_simple_intercon_0_0"));
	registerTlmSocket("data_M_AXI_0_tlm_aximm_write_socket",inst5->target_0_wr_socket);
	pfm_dynamic_xtlm_simple_intercon_0_0_sc*  inst6=dynamic_cast<pfm_dynamic_xtlm_simple_intercon_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xtlm_simple_intercon_0_0"));
	registerTlmSocket("data_M_AXI_3_tlm_aximm_read_socket",inst6->target_3_rd_socket);
	pfm_dynamic_xtlm_simple_intercon_0_0_sc*  inst7=dynamic_cast<pfm_dynamic_xtlm_simple_intercon_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xtlm_simple_intercon_0_0"));
	registerTlmSocket("data_M_AXI_3_tlm_aximm_write_socket",inst7->target_3_wr_socket);
	pfm_dynamic_xtlm_simple_intercon_0_0_sc*  inst8=dynamic_cast<pfm_dynamic_xtlm_simple_intercon_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xtlm_simple_intercon_0_0"));
	registerTlmSocket("data_M_AXI_1_tlm_aximm_read_socket",inst8->target_1_rd_socket);
	pfm_dynamic_xtlm_simple_intercon_0_0_sc*  inst9=dynamic_cast<pfm_dynamic_xtlm_simple_intercon_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xtlm_simple_intercon_0_0"));
	registerTlmSocket("data_M_AXI_1_tlm_aximm_write_socket",inst9->target_1_wr_socket);
	pfm_dynamic_xtlm_simple_intercon_0_0_sc*  inst10=dynamic_cast<pfm_dynamic_xtlm_simple_intercon_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xtlm_simple_intercon_0_0"));
	registerTlmSocket("data_M_AXI_2_tlm_aximm_read_socket",inst10->target_2_rd_socket);
	pfm_dynamic_xtlm_simple_intercon_0_0_sc*  inst11=dynamic_cast<pfm_dynamic_xtlm_simple_intercon_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xtlm_simple_intercon_0_0"));
	registerTlmSocket("data_M_AXI_2_tlm_aximm_write_socket",inst11->target_2_wr_socket);
}

void pfm_dynamic_sci::before_end_of_elaboration() {
	
	pfm_dynamic_dpa_mon0_0_sc*  inst_0=dynamic_cast<pfm_dynamic_dpa_mon0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_mon0_0"));
	pfm_dynamic_dpa_hub_0_sc*  inst_1=dynamic_cast<pfm_dynamic_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_0 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_0");
	
	if(inst_0==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_mon0_0_sc"<<std::endl;
	}
	if(inst_1==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_0!=NULL && inst_1!=NULL) {
		inst_0->trace_skt->bind(*(log_inst_0->tar_skt));
		log_inst_0->init_skt->bind(*(inst_1->trace_socket0));
	}
	
	pfm_dynamic_dpa_mon1_0_sc*  inst_4=dynamic_cast<pfm_dynamic_dpa_mon1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_mon1_0"));
	pfm_dynamic_dpa_hub_0_sc*  inst_5=dynamic_cast<pfm_dynamic_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_1 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_1");
	
	if(inst_4==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_mon1_0_sc"<<std::endl;
	}
	if(inst_5==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_4!=NULL && inst_5!=NULL) {
		inst_4->wr_trace_socket->bind(*(log_inst_1->tar_skt));
		log_inst_1->init_skt->bind(*(inst_5->trace_socket1));
	}
	
	pfm_dynamic_dpa_mon1_0_sc*  inst_8=dynamic_cast<pfm_dynamic_dpa_mon1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_mon1_0"));
	pfm_dynamic_dpa_hub_0_sc*  inst_9=dynamic_cast<pfm_dynamic_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_2 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_2");
	
	if(inst_8==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_mon1_0_sc"<<std::endl;
	}
	if(inst_9==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_8!=NULL && inst_9!=NULL) {
		inst_8->rd_trace_socket->bind(*(log_inst_2->tar_skt));
		log_inst_2->init_skt->bind(*(inst_9->trace_socket2));
	}
	
	pfm_dynamic_dpa_mon2_0_sc*  inst_12=dynamic_cast<pfm_dynamic_dpa_mon2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_mon2_0"));
	pfm_dynamic_dpa_hub_0_sc*  inst_13=dynamic_cast<pfm_dynamic_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_3 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_3");
	
	if(inst_12==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_mon2_0_sc"<<std::endl;
	}
	if(inst_13==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_12!=NULL && inst_13!=NULL) {
		inst_12->trace_skt->bind(*(log_inst_3->tar_skt));
		log_inst_3->init_skt->bind(*(inst_13->trace_socket3));
	}
	
	pfm_dynamic_dpa_mon3_0_sc*  inst_16=dynamic_cast<pfm_dynamic_dpa_mon3_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_mon3_0"));
	pfm_dynamic_dpa_hub_0_sc*  inst_17=dynamic_cast<pfm_dynamic_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_4 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_4");
	
	if(inst_16==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_mon3_0_sc"<<std::endl;
	}
	if(inst_17==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_16!=NULL && inst_17!=NULL) {
		inst_16->wr_trace_socket->bind(*(log_inst_4->tar_skt));
		log_inst_4->init_skt->bind(*(inst_17->trace_socket4));
	}
	
	pfm_dynamic_dpa_mon3_0_sc*  inst_20=dynamic_cast<pfm_dynamic_dpa_mon3_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_mon3_0"));
	pfm_dynamic_dpa_hub_0_sc*  inst_21=dynamic_cast<pfm_dynamic_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_hub_0"));
	xtlm_axis_transaction_logger* log_inst_5 = new xtlm_axis_transaction_logger("xtlm_axis_transaction_logger_5");
	
	if(inst_20==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_mon3_0_sc"<<std::endl;
	}
	if(inst_21==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_20!=NULL && inst_21!=NULL) {
		inst_20->rd_trace_socket->bind(*(log_inst_5->tar_skt));
		log_inst_5->init_skt->bind(*(inst_21->trace_socket5));
	}
	
	pfm_dynamic_xtlm_simple_intercon_0_0_sc*  inst_24=dynamic_cast<pfm_dynamic_xtlm_simple_intercon_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xtlm_simple_intercon_0_0"));
	pfm_dynamic_icn_pass_0_0_sc*  inst_25=dynamic_cast<pfm_dynamic_icn_pass_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_icn_pass_0_0"));
	xtlm_aximm_transaction_logger* log_inst_6 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_6");
	log_inst_6->setProxyRef(inst_24, inst_25, "masterSocket_6", "slaveSocket_6", log_inst_6->m_transactionLogger);
	
	if(inst_24==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xtlm_simple_intercon_0_0_sc"<<std::endl;
	}
	if(inst_25==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_icn_pass_0_0_sc"<<std::endl;
	}
	
	if (inst_24!=NULL && inst_25!=NULL) {
		inst_24->initiator_0_rd_socket->bind(*(log_inst_6->tar_rd_skt));
		log_inst_6->init_rd_skt->bind(*(inst_25->target_0_rd_socket));
	}
	
	pfm_dynamic_xtlm_simple_intercon_0_0_sc*  inst_28=dynamic_cast<pfm_dynamic_xtlm_simple_intercon_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xtlm_simple_intercon_0_0"));
	pfm_dynamic_icn_pass_0_0_sc*  inst_29=dynamic_cast<pfm_dynamic_icn_pass_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_icn_pass_0_0"));
	
	if(inst_28==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xtlm_simple_intercon_0_0_sc"<<std::endl;
	}
	if(inst_29==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_icn_pass_0_0_sc"<<std::endl;
	}
	
	if (inst_28!=NULL && inst_29!=NULL) {
		inst_28->initiator_0_wr_socket->bind(*(log_inst_6->tar_wr_skt));
		log_inst_6->init_wr_skt->bind(*(inst_29->target_0_wr_socket));
	}
	
	pfm_dynamic_icn_pass_0_0_sc*  inst_32=dynamic_cast<pfm_dynamic_icn_pass_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_icn_pass_0_0"));
	pfm_dynamic_memory_subsystem_0_sc*  inst_33=dynamic_cast<pfm_dynamic_memory_subsystem_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_memory_subsystem_0"));
	xtlm_aximm_transaction_logger* log_inst_7 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_7");
	log_inst_7->setProxyRef(inst_32, inst_33, "masterSocket_7", "slaveSocket_7", log_inst_7->m_transactionLogger);
	
	if(inst_32==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_icn_pass_0_0_sc"<<std::endl;
	}
	if(inst_33==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_memory_subsystem_0_sc"<<std::endl;
	}
	
	if (inst_32!=NULL && inst_33!=NULL) {
		inst_32->initiator_0_rd_socket->bind(*(log_inst_7->tar_rd_skt));
		log_inst_7->init_rd_skt->bind(*(inst_33->S00_AXI_tlm_aximm_read_socket));
	}
	
	pfm_dynamic_icn_pass_0_0_sc*  inst_36=dynamic_cast<pfm_dynamic_icn_pass_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_icn_pass_0_0"));
	pfm_dynamic_memory_subsystem_0_sc*  inst_37=dynamic_cast<pfm_dynamic_memory_subsystem_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_memory_subsystem_0"));
	
	if(inst_36==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_icn_pass_0_0_sc"<<std::endl;
	}
	if(inst_37==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_memory_subsystem_0_sc"<<std::endl;
	}
	
	if (inst_36!=NULL && inst_37!=NULL) {
		inst_36->initiator_0_wr_socket->bind(*(log_inst_7->tar_wr_skt));
		log_inst_7->init_wr_skt->bind(*(inst_37->S00_AXI_tlm_aximm_write_socket));
	}
	
	pfm_dynamic_memory_subsystem_0_sc*  inst_40=dynamic_cast<pfm_dynamic_memory_subsystem_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_memory_subsystem_0"));
	pfm_dynamic_sim_ddr_0_0_sc*  inst_41=dynamic_cast<pfm_dynamic_sim_ddr_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_sim_ddr_0_0"));
	xtlm_aximm_transaction_logger* log_inst_8 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_8");
	log_inst_8->setProxyRef(inst_40, inst_41, "masterSocket_8", "slaveSocket_8", log_inst_8->m_transactionLogger);
	
	if(inst_40==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_memory_subsystem_0_sc"<<std::endl;
	}
	if(inst_41==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_sim_ddr_0_0_sc"<<std::endl;
	}
	
	if (inst_40!=NULL && inst_41!=NULL) {
		inst_40->M00_AXI_tlm_aximm_read_socket->bind(*(log_inst_8->tar_rd_skt));
		log_inst_8->init_rd_skt->bind(*(inst_41->C0_DDR_SAXI_rd_socket));
	}
	
	pfm_dynamic_memory_subsystem_0_sc*  inst_44=dynamic_cast<pfm_dynamic_memory_subsystem_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_memory_subsystem_0"));
	pfm_dynamic_sim_ddr_0_0_sc*  inst_45=dynamic_cast<pfm_dynamic_sim_ddr_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_sim_ddr_0_0"));
	
	if(inst_44==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_memory_subsystem_0_sc"<<std::endl;
	}
	if(inst_45==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_sim_ddr_0_0_sc"<<std::endl;
	}
	
	if (inst_44!=NULL && inst_45!=NULL) {
		inst_44->M00_AXI_tlm_aximm_write_socket->bind(*(log_inst_8->tar_wr_skt));
		log_inst_8->init_wr_skt->bind(*(inst_45->C0_DDR_SAXI_wr_socket));
	}
	
	pfm_dynamic_xtlm_simple_intercon_0_0_sc*  inst_48=dynamic_cast<pfm_dynamic_xtlm_simple_intercon_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xtlm_simple_intercon_0_0"));
	pfm_dynamic_icn_pass_1_0_sc*  inst_49=dynamic_cast<pfm_dynamic_icn_pass_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_icn_pass_1_0"));
	xtlm_aximm_transaction_logger* log_inst_9 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_9");
	log_inst_9->setProxyRef(inst_48, inst_49, "masterSocket_9", "slaveSocket_9", log_inst_9->m_transactionLogger);
	
	if(inst_48==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xtlm_simple_intercon_0_0_sc"<<std::endl;
	}
	if(inst_49==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_icn_pass_1_0_sc"<<std::endl;
	}
	
	if (inst_48!=NULL && inst_49!=NULL) {
		inst_48->initiator_1_rd_socket->bind(*(log_inst_9->tar_rd_skt));
		log_inst_9->init_rd_skt->bind(*(inst_49->target_0_rd_socket));
	}
	
	pfm_dynamic_xtlm_simple_intercon_0_0_sc*  inst_52=dynamic_cast<pfm_dynamic_xtlm_simple_intercon_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xtlm_simple_intercon_0_0"));
	pfm_dynamic_icn_pass_1_0_sc*  inst_53=dynamic_cast<pfm_dynamic_icn_pass_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_icn_pass_1_0"));
	
	if(inst_52==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xtlm_simple_intercon_0_0_sc"<<std::endl;
	}
	if(inst_53==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_icn_pass_1_0_sc"<<std::endl;
	}
	
	if (inst_52!=NULL && inst_53!=NULL) {
		inst_52->initiator_1_wr_socket->bind(*(log_inst_9->tar_wr_skt));
		log_inst_9->init_wr_skt->bind(*(inst_53->target_0_wr_socket));
	}
	
	pfm_dynamic_icn_pass_1_0_sc*  inst_56=dynamic_cast<pfm_dynamic_icn_pass_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_icn_pass_1_0"));
	pfm_dynamic_memory_subsystem_0_sc*  inst_57=dynamic_cast<pfm_dynamic_memory_subsystem_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_memory_subsystem_0"));
	xtlm_aximm_transaction_logger* log_inst_10 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_10");
	log_inst_10->setProxyRef(inst_56, inst_57, "masterSocket_10", "slaveSocket_10", log_inst_10->m_transactionLogger);
	
	if(inst_56==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_icn_pass_1_0_sc"<<std::endl;
	}
	if(inst_57==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_memory_subsystem_0_sc"<<std::endl;
	}
	
	if (inst_56!=NULL && inst_57!=NULL) {
		inst_56->initiator_0_rd_socket->bind(*(log_inst_10->tar_rd_skt));
		log_inst_10->init_rd_skt->bind(*(inst_57->S01_AXI_tlm_aximm_read_socket));
	}
	
	pfm_dynamic_icn_pass_1_0_sc*  inst_60=dynamic_cast<pfm_dynamic_icn_pass_1_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_icn_pass_1_0"));
	pfm_dynamic_memory_subsystem_0_sc*  inst_61=dynamic_cast<pfm_dynamic_memory_subsystem_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_memory_subsystem_0"));
	
	if(inst_60==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_icn_pass_1_0_sc"<<std::endl;
	}
	if(inst_61==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_memory_subsystem_0_sc"<<std::endl;
	}
	
	if (inst_60!=NULL && inst_61!=NULL) {
		inst_60->initiator_0_wr_socket->bind(*(log_inst_10->tar_wr_skt));
		log_inst_10->init_wr_skt->bind(*(inst_61->S01_AXI_tlm_aximm_write_socket));
	}
	
	pfm_dynamic_xtlm_simple_intercon_0_0_sc*  inst_64=dynamic_cast<pfm_dynamic_xtlm_simple_intercon_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xtlm_simple_intercon_0_0"));
	pfm_dynamic_icn_pass_2_0_sc*  inst_65=dynamic_cast<pfm_dynamic_icn_pass_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_icn_pass_2_0"));
	xtlm_aximm_transaction_logger* log_inst_11 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_11");
	log_inst_11->setProxyRef(inst_64, inst_65, "masterSocket_11", "slaveSocket_11", log_inst_11->m_transactionLogger);
	
	if(inst_64==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xtlm_simple_intercon_0_0_sc"<<std::endl;
	}
	if(inst_65==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_icn_pass_2_0_sc"<<std::endl;
	}
	
	if (inst_64!=NULL && inst_65!=NULL) {
		inst_64->initiator_2_rd_socket->bind(*(log_inst_11->tar_rd_skt));
		log_inst_11->init_rd_skt->bind(*(inst_65->target_0_rd_socket));
	}
	
	pfm_dynamic_xtlm_simple_intercon_0_0_sc*  inst_68=dynamic_cast<pfm_dynamic_xtlm_simple_intercon_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xtlm_simple_intercon_0_0"));
	pfm_dynamic_icn_pass_2_0_sc*  inst_69=dynamic_cast<pfm_dynamic_icn_pass_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_icn_pass_2_0"));
	
	if(inst_68==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xtlm_simple_intercon_0_0_sc"<<std::endl;
	}
	if(inst_69==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_icn_pass_2_0_sc"<<std::endl;
	}
	
	if (inst_68!=NULL && inst_69!=NULL) {
		inst_68->initiator_2_wr_socket->bind(*(log_inst_11->tar_wr_skt));
		log_inst_11->init_wr_skt->bind(*(inst_69->target_0_wr_socket));
	}
	
	pfm_dynamic_icn_pass_2_0_sc*  inst_72=dynamic_cast<pfm_dynamic_icn_pass_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_icn_pass_2_0"));
	pfm_dynamic_memory_subsystem_0_sc*  inst_73=dynamic_cast<pfm_dynamic_memory_subsystem_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_memory_subsystem_0"));
	xtlm_aximm_transaction_logger* log_inst_12 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_12");
	log_inst_12->setProxyRef(inst_72, inst_73, "masterSocket_12", "slaveSocket_12", log_inst_12->m_transactionLogger);
	
	if(inst_72==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_icn_pass_2_0_sc"<<std::endl;
	}
	if(inst_73==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_memory_subsystem_0_sc"<<std::endl;
	}
	
	if (inst_72!=NULL && inst_73!=NULL) {
		inst_72->initiator_0_rd_socket->bind(*(log_inst_12->tar_rd_skt));
		log_inst_12->init_rd_skt->bind(*(inst_73->S02_AXI_tlm_aximm_read_socket));
	}
	
	pfm_dynamic_icn_pass_2_0_sc*  inst_76=dynamic_cast<pfm_dynamic_icn_pass_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_icn_pass_2_0"));
	pfm_dynamic_memory_subsystem_0_sc*  inst_77=dynamic_cast<pfm_dynamic_memory_subsystem_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_memory_subsystem_0"));
	
	if(inst_76==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_icn_pass_2_0_sc"<<std::endl;
	}
	if(inst_77==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_memory_subsystem_0_sc"<<std::endl;
	}
	
	if (inst_76!=NULL && inst_77!=NULL) {
		inst_76->initiator_0_wr_socket->bind(*(log_inst_12->tar_wr_skt));
		log_inst_12->init_wr_skt->bind(*(inst_77->S02_AXI_tlm_aximm_write_socket));
	}
	
	pfm_dynamic_memory_subsystem_0_sc*  inst_80=dynamic_cast<pfm_dynamic_memory_subsystem_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_memory_subsystem_0"));
	pfm_dynamic_sim_ddr_2_0_sc*  inst_81=dynamic_cast<pfm_dynamic_sim_ddr_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_sim_ddr_2_0"));
	xtlm_aximm_transaction_logger* log_inst_13 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_13");
	log_inst_13->setProxyRef(inst_80, inst_81, "masterSocket_13", "slaveSocket_13", log_inst_13->m_transactionLogger);
	
	if(inst_80==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_memory_subsystem_0_sc"<<std::endl;
	}
	if(inst_81==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_sim_ddr_2_0_sc"<<std::endl;
	}
	
	if (inst_80!=NULL && inst_81!=NULL) {
		inst_80->M02_AXI_tlm_aximm_read_socket->bind(*(log_inst_13->tar_rd_skt));
		log_inst_13->init_rd_skt->bind(*(inst_81->C0_DDR_SAXI_rd_socket));
	}
	
	pfm_dynamic_memory_subsystem_0_sc*  inst_84=dynamic_cast<pfm_dynamic_memory_subsystem_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_memory_subsystem_0"));
	pfm_dynamic_sim_ddr_2_0_sc*  inst_85=dynamic_cast<pfm_dynamic_sim_ddr_2_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_sim_ddr_2_0"));
	
	if(inst_84==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_memory_subsystem_0_sc"<<std::endl;
	}
	if(inst_85==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_sim_ddr_2_0_sc"<<std::endl;
	}
	
	if (inst_84!=NULL && inst_85!=NULL) {
		inst_84->M02_AXI_tlm_aximm_write_socket->bind(*(log_inst_13->tar_wr_skt));
		log_inst_13->init_wr_skt->bind(*(inst_85->C0_DDR_SAXI_wr_socket));
	}
	
	pfm_dynamic_xtlm_simple_intercon_0_0_sc*  inst_88=dynamic_cast<pfm_dynamic_xtlm_simple_intercon_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xtlm_simple_intercon_0_0"));
	pfm_dynamic_icn_pass_3_0_sc*  inst_89=dynamic_cast<pfm_dynamic_icn_pass_3_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_icn_pass_3_0"));
	xtlm_aximm_transaction_logger* log_inst_14 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_14");
	log_inst_14->setProxyRef(inst_88, inst_89, "masterSocket_14", "slaveSocket_14", log_inst_14->m_transactionLogger);
	
	if(inst_88==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xtlm_simple_intercon_0_0_sc"<<std::endl;
	}
	if(inst_89==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_icn_pass_3_0_sc"<<std::endl;
	}
	
	if (inst_88!=NULL && inst_89!=NULL) {
		inst_88->initiator_3_rd_socket->bind(*(log_inst_14->tar_rd_skt));
		log_inst_14->init_rd_skt->bind(*(inst_89->target_0_rd_socket));
	}
	
	pfm_dynamic_xtlm_simple_intercon_0_0_sc*  inst_92=dynamic_cast<pfm_dynamic_xtlm_simple_intercon_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xtlm_simple_intercon_0_0"));
	pfm_dynamic_icn_pass_3_0_sc*  inst_93=dynamic_cast<pfm_dynamic_icn_pass_3_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_icn_pass_3_0"));
	
	if(inst_92==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xtlm_simple_intercon_0_0_sc"<<std::endl;
	}
	if(inst_93==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_icn_pass_3_0_sc"<<std::endl;
	}
	
	if (inst_92!=NULL && inst_93!=NULL) {
		inst_92->initiator_3_wr_socket->bind(*(log_inst_14->tar_wr_skt));
		log_inst_14->init_wr_skt->bind(*(inst_93->target_0_wr_socket));
	}
	
	pfm_dynamic_icn_pass_3_0_sc*  inst_96=dynamic_cast<pfm_dynamic_icn_pass_3_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_icn_pass_3_0"));
	pfm_dynamic_memory_subsystem_0_sc*  inst_97=dynamic_cast<pfm_dynamic_memory_subsystem_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_memory_subsystem_0"));
	xtlm_aximm_transaction_logger* log_inst_15 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_15");
	log_inst_15->setProxyRef(inst_96, inst_97, "masterSocket_15", "slaveSocket_15", log_inst_15->m_transactionLogger);
	
	if(inst_96==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_icn_pass_3_0_sc"<<std::endl;
	}
	if(inst_97==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_memory_subsystem_0_sc"<<std::endl;
	}
	
	if (inst_96!=NULL && inst_97!=NULL) {
		inst_96->initiator_0_rd_socket->bind(*(log_inst_15->tar_rd_skt));
		log_inst_15->init_rd_skt->bind(*(inst_97->S03_AXI_tlm_aximm_read_socket));
	}
	
	pfm_dynamic_icn_pass_3_0_sc*  inst_100=dynamic_cast<pfm_dynamic_icn_pass_3_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_icn_pass_3_0"));
	pfm_dynamic_memory_subsystem_0_sc*  inst_101=dynamic_cast<pfm_dynamic_memory_subsystem_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_memory_subsystem_0"));
	
	if(inst_100==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_icn_pass_3_0_sc"<<std::endl;
	}
	if(inst_101==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_memory_subsystem_0_sc"<<std::endl;
	}
	
	if (inst_100!=NULL && inst_101!=NULL) {
		inst_100->initiator_0_wr_socket->bind(*(log_inst_15->tar_wr_skt));
		log_inst_15->init_wr_skt->bind(*(inst_101->S03_AXI_tlm_aximm_write_socket));
	}
	
	pfm_dynamic_memory_subsystem_0_sc*  inst_104=dynamic_cast<pfm_dynamic_memory_subsystem_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_memory_subsystem_0"));
	pfm_dynamic_sim_ddr_3_0_sc*  inst_105=dynamic_cast<pfm_dynamic_sim_ddr_3_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_sim_ddr_3_0"));
	xtlm_aximm_transaction_logger* log_inst_16 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_16");
	log_inst_16->setProxyRef(inst_104, inst_105, "masterSocket_16", "slaveSocket_16", log_inst_16->m_transactionLogger);
	
	if(inst_104==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_memory_subsystem_0_sc"<<std::endl;
	}
	if(inst_105==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_sim_ddr_3_0_sc"<<std::endl;
	}
	
	if (inst_104!=NULL && inst_105!=NULL) {
		inst_104->M03_AXI_tlm_aximm_read_socket->bind(*(log_inst_16->tar_rd_skt));
		log_inst_16->init_rd_skt->bind(*(inst_105->C0_DDR_SAXI_rd_socket));
	}
	
	pfm_dynamic_memory_subsystem_0_sc*  inst_108=dynamic_cast<pfm_dynamic_memory_subsystem_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_memory_subsystem_0"));
	pfm_dynamic_sim_ddr_3_0_sc*  inst_109=dynamic_cast<pfm_dynamic_sim_ddr_3_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_sim_ddr_3_0"));
	
	if(inst_108==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_memory_subsystem_0_sc"<<std::endl;
	}
	if(inst_109==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_sim_ddr_3_0_sc"<<std::endl;
	}
	
	if (inst_108!=NULL && inst_109!=NULL) {
		inst_108->M03_AXI_tlm_aximm_write_socket->bind(*(log_inst_16->tar_wr_skt));
		log_inst_16->init_wr_skt->bind(*(inst_109->C0_DDR_SAXI_wr_socket));
	}
	
	pfm_dynamic_xtlm_simple_intercon_0_0_sc*  inst_112=dynamic_cast<pfm_dynamic_xtlm_simple_intercon_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xtlm_simple_intercon_0_0"));
	pfm_dynamic_dpa_hub_0_sc*  inst_113=dynamic_cast<pfm_dynamic_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_hub_0"));
	xtlm_aximm_transaction_logger* log_inst_17 = new xtlm_aximm_transaction_logger("xtlm_aximm_transaction_logger_17");
	log_inst_17->setProxyRef(inst_112, inst_113, "masterSocket_17", "slaveSocket_17", log_inst_17->m_transactionLogger);
	
	if(inst_112==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xtlm_simple_intercon_0_0_sc"<<std::endl;
	}
	if(inst_113==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_112!=NULL && inst_113!=NULL) {
		inst_112->initiator_4_rd_socket->bind(*(log_inst_17->tar_rd_skt));
		log_inst_17->init_rd_skt->bind(*(inst_113->s_aximm_rd_socket));
	}
	
	pfm_dynamic_xtlm_simple_intercon_0_0_sc*  inst_116=dynamic_cast<pfm_dynamic_xtlm_simple_intercon_0_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_xtlm_simple_intercon_0_0"));
	pfm_dynamic_dpa_hub_0_sc*  inst_117=dynamic_cast<pfm_dynamic_dpa_hub_0_sc*>(xsc::utils::xsc_sim_manager::getInstancePtr("pfm_dynamic_dpa_hub_0"));
	
	if(inst_116==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_xtlm_simple_intercon_0_0_sc"<<std::endl;
	}
	if(inst_117==NULL) {
		std::cerr<<"Error: While binding sockets cannot find socket object instance to bind pfm_dynamic_dpa_hub_0_sc"<<std::endl;
	}
	
	if (inst_116!=NULL && inst_117!=NULL) {
		inst_116->initiator_4_wr_socket->bind(*(log_inst_17->tar_wr_skt));
		log_inst_17->init_wr_skt->bind(*(inst_117->s_aximm_wr_socket));
	}
	
}
#ifdef MTI_SYSTEMC
SC_MODULE_EXPORT(pfm_dynamic_sci);
#endif

#ifdef XM_SYSTEMC
XMSC_MODULE_EXPORT(pfm_dynamic_sci);
#endif

#ifdef RIVIERA
SC_MODULE_EXPORT(pfm_dynamic_sci);
#endif

