catch {::common::set_param -quiet hls.xocc.mode csynth};
# 
# Hls run script generated by the compiler
# 

set vpp_optimize_level 0
open_project krnl_vadd
set_top krnl_vadd
add_files "/home/centos/workspace/vector_add_lab_xilinx/src/krnl_vadd.cpp" -cflags " -g -I /home/centos/workspace/vector_add_lab_xilinx/src "
open_solution -flow_target vitis solution
set_part xcvu9p-flgb2104-2-i
create_clock -period 250.000000MHz -name default
config_rtl -kernel_profile
config_export -vivado_optimization_level $vpp_optimize_level
config_dataflow -strict_mode warning
config_debug -enable
set_clock_uncertainty 27.000000%
config_rtl -m_axi_conservative_mode=1
config_interface -m_axi_addr64
config_interface -default_slave_interface s_axilite
config_export -format ip_catalog -ipname krnl_vadd
csynth_design
export_design
close_project
puts "HLS completed successfully"
exit
