#
# This file was created by Xilinx Vitis tool.
#


#
# tools
#

RM = rm -f
RMDIR = rm -rf


XILINX_VITIS ?= /opt/Xilinx/Vitis/2020.1

VPP ?= ${XILINX_VITIS}/bin/v++




VITIS_PLATFORM = xilinx_aws-vu9p-f1_shell-v04261818_201920_2
VITIS_PLATFORM_DIR = /home/centos/src/project_data/aws-fpga/Vitis/aws_platform/xilinx_aws-vu9p-f1_shell-v04261818_201920_2
VITIS_PLATFORM_PATH = $(VITIS_PLATFORM_DIR)/xilinx_aws-vu9p-f1_shell-v04261818_201920_2.xpfm


#
# variables
#


#
# primary build targets
#

all: package

package:


clean:
	$(RMDIR) ./package.build
	${RMDIR} package

.PHONY: all package clean


