// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module krnl_idct_krnl_idct_dataflow (
        m_axi_gmem0_AWVALID,
        m_axi_gmem0_AWREADY,
        m_axi_gmem0_AWADDR,
        m_axi_gmem0_AWID,
        m_axi_gmem0_AWLEN,
        m_axi_gmem0_AWSIZE,
        m_axi_gmem0_AWBURST,
        m_axi_gmem0_AWLOCK,
        m_axi_gmem0_AWCACHE,
        m_axi_gmem0_AWPROT,
        m_axi_gmem0_AWQOS,
        m_axi_gmem0_AWREGION,
        m_axi_gmem0_AWUSER,
        m_axi_gmem0_WVALID,
        m_axi_gmem0_WREADY,
        m_axi_gmem0_WDATA,
        m_axi_gmem0_WSTRB,
        m_axi_gmem0_WLAST,
        m_axi_gmem0_WID,
        m_axi_gmem0_WUSER,
        m_axi_gmem0_ARVALID,
        m_axi_gmem0_ARREADY,
        m_axi_gmem0_ARADDR,
        m_axi_gmem0_ARID,
        m_axi_gmem0_ARLEN,
        m_axi_gmem0_ARSIZE,
        m_axi_gmem0_ARBURST,
        m_axi_gmem0_ARLOCK,
        m_axi_gmem0_ARCACHE,
        m_axi_gmem0_ARPROT,
        m_axi_gmem0_ARQOS,
        m_axi_gmem0_ARREGION,
        m_axi_gmem0_ARUSER,
        m_axi_gmem0_RVALID,
        m_axi_gmem0_RREADY,
        m_axi_gmem0_RDATA,
        m_axi_gmem0_RLAST,
        m_axi_gmem0_RID,
        m_axi_gmem0_RUSER,
        m_axi_gmem0_RRESP,
        m_axi_gmem0_BVALID,
        m_axi_gmem0_BREADY,
        m_axi_gmem0_BRESP,
        m_axi_gmem0_BID,
        m_axi_gmem0_BUSER,
        m_axi_gmem1_AWVALID,
        m_axi_gmem1_AWREADY,
        m_axi_gmem1_AWADDR,
        m_axi_gmem1_AWID,
        m_axi_gmem1_AWLEN,
        m_axi_gmem1_AWSIZE,
        m_axi_gmem1_AWBURST,
        m_axi_gmem1_AWLOCK,
        m_axi_gmem1_AWCACHE,
        m_axi_gmem1_AWPROT,
        m_axi_gmem1_AWQOS,
        m_axi_gmem1_AWREGION,
        m_axi_gmem1_AWUSER,
        m_axi_gmem1_WVALID,
        m_axi_gmem1_WREADY,
        m_axi_gmem1_WDATA,
        m_axi_gmem1_WSTRB,
        m_axi_gmem1_WLAST,
        m_axi_gmem1_WID,
        m_axi_gmem1_WUSER,
        m_axi_gmem1_ARVALID,
        m_axi_gmem1_ARREADY,
        m_axi_gmem1_ARADDR,
        m_axi_gmem1_ARID,
        m_axi_gmem1_ARLEN,
        m_axi_gmem1_ARSIZE,
        m_axi_gmem1_ARBURST,
        m_axi_gmem1_ARLOCK,
        m_axi_gmem1_ARCACHE,
        m_axi_gmem1_ARPROT,
        m_axi_gmem1_ARQOS,
        m_axi_gmem1_ARREGION,
        m_axi_gmem1_ARUSER,
        m_axi_gmem1_RVALID,
        m_axi_gmem1_RREADY,
        m_axi_gmem1_RDATA,
        m_axi_gmem1_RLAST,
        m_axi_gmem1_RID,
        m_axi_gmem1_RUSER,
        m_axi_gmem1_RRESP,
        m_axi_gmem1_BVALID,
        m_axi_gmem1_BREADY,
        m_axi_gmem1_BRESP,
        m_axi_gmem1_BID,
        m_axi_gmem1_BUSER,
        m_axi_gmem2_AWVALID,
        m_axi_gmem2_AWREADY,
        m_axi_gmem2_AWADDR,
        m_axi_gmem2_AWID,
        m_axi_gmem2_AWLEN,
        m_axi_gmem2_AWSIZE,
        m_axi_gmem2_AWBURST,
        m_axi_gmem2_AWLOCK,
        m_axi_gmem2_AWCACHE,
        m_axi_gmem2_AWPROT,
        m_axi_gmem2_AWQOS,
        m_axi_gmem2_AWREGION,
        m_axi_gmem2_AWUSER,
        m_axi_gmem2_WVALID,
        m_axi_gmem2_WREADY,
        m_axi_gmem2_WDATA,
        m_axi_gmem2_WSTRB,
        m_axi_gmem2_WLAST,
        m_axi_gmem2_WID,
        m_axi_gmem2_WUSER,
        m_axi_gmem2_ARVALID,
        m_axi_gmem2_ARREADY,
        m_axi_gmem2_ARADDR,
        m_axi_gmem2_ARID,
        m_axi_gmem2_ARLEN,
        m_axi_gmem2_ARSIZE,
        m_axi_gmem2_ARBURST,
        m_axi_gmem2_ARLOCK,
        m_axi_gmem2_ARCACHE,
        m_axi_gmem2_ARPROT,
        m_axi_gmem2_ARQOS,
        m_axi_gmem2_ARREGION,
        m_axi_gmem2_ARUSER,
        m_axi_gmem2_RVALID,
        m_axi_gmem2_RREADY,
        m_axi_gmem2_RDATA,
        m_axi_gmem2_RLAST,
        m_axi_gmem2_RID,
        m_axi_gmem2_RUSER,
        m_axi_gmem2_RRESP,
        m_axi_gmem2_BVALID,
        m_axi_gmem2_BREADY,
        m_axi_gmem2_BRESP,
        m_axi_gmem2_BID,
        m_axi_gmem2_BUSER,
        block_r,
        q,
        voutp,
        ignore_dc,
        blocks,
        ap_clk,
        ap_rst,
        block_r_ap_vld,
        q_ap_vld,
        voutp_ap_vld,
        ignore_dc_ap_vld,
        blocks_ap_vld,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue,
        ap_ext_blocking_n,
        ap_str_blocking_n,
        ap_int_blocking_n
);


output   m_axi_gmem0_AWVALID;
input   m_axi_gmem0_AWREADY;
output  [63:0] m_axi_gmem0_AWADDR;
output  [0:0] m_axi_gmem0_AWID;
output  [31:0] m_axi_gmem0_AWLEN;
output  [2:0] m_axi_gmem0_AWSIZE;
output  [1:0] m_axi_gmem0_AWBURST;
output  [1:0] m_axi_gmem0_AWLOCK;
output  [3:0] m_axi_gmem0_AWCACHE;
output  [2:0] m_axi_gmem0_AWPROT;
output  [3:0] m_axi_gmem0_AWQOS;
output  [3:0] m_axi_gmem0_AWREGION;
output  [0:0] m_axi_gmem0_AWUSER;
output   m_axi_gmem0_WVALID;
input   m_axi_gmem0_WREADY;
output  [511:0] m_axi_gmem0_WDATA;
output  [63:0] m_axi_gmem0_WSTRB;
output   m_axi_gmem0_WLAST;
output  [0:0] m_axi_gmem0_WID;
output  [0:0] m_axi_gmem0_WUSER;
output   m_axi_gmem0_ARVALID;
input   m_axi_gmem0_ARREADY;
output  [63:0] m_axi_gmem0_ARADDR;
output  [0:0] m_axi_gmem0_ARID;
output  [31:0] m_axi_gmem0_ARLEN;
output  [2:0] m_axi_gmem0_ARSIZE;
output  [1:0] m_axi_gmem0_ARBURST;
output  [1:0] m_axi_gmem0_ARLOCK;
output  [3:0] m_axi_gmem0_ARCACHE;
output  [2:0] m_axi_gmem0_ARPROT;
output  [3:0] m_axi_gmem0_ARQOS;
output  [3:0] m_axi_gmem0_ARREGION;
output  [0:0] m_axi_gmem0_ARUSER;
input   m_axi_gmem0_RVALID;
output   m_axi_gmem0_RREADY;
input  [511:0] m_axi_gmem0_RDATA;
input   m_axi_gmem0_RLAST;
input  [0:0] m_axi_gmem0_RID;
input  [0:0] m_axi_gmem0_RUSER;
input  [1:0] m_axi_gmem0_RRESP;
input   m_axi_gmem0_BVALID;
output   m_axi_gmem0_BREADY;
input  [1:0] m_axi_gmem0_BRESP;
input  [0:0] m_axi_gmem0_BID;
input  [0:0] m_axi_gmem0_BUSER;
output   m_axi_gmem1_AWVALID;
input   m_axi_gmem1_AWREADY;
output  [63:0] m_axi_gmem1_AWADDR;
output  [0:0] m_axi_gmem1_AWID;
output  [31:0] m_axi_gmem1_AWLEN;
output  [2:0] m_axi_gmem1_AWSIZE;
output  [1:0] m_axi_gmem1_AWBURST;
output  [1:0] m_axi_gmem1_AWLOCK;
output  [3:0] m_axi_gmem1_AWCACHE;
output  [2:0] m_axi_gmem1_AWPROT;
output  [3:0] m_axi_gmem1_AWQOS;
output  [3:0] m_axi_gmem1_AWREGION;
output  [0:0] m_axi_gmem1_AWUSER;
output   m_axi_gmem1_WVALID;
input   m_axi_gmem1_WREADY;
output  [511:0] m_axi_gmem1_WDATA;
output  [63:0] m_axi_gmem1_WSTRB;
output   m_axi_gmem1_WLAST;
output  [0:0] m_axi_gmem1_WID;
output  [0:0] m_axi_gmem1_WUSER;
output   m_axi_gmem1_ARVALID;
input   m_axi_gmem1_ARREADY;
output  [63:0] m_axi_gmem1_ARADDR;
output  [0:0] m_axi_gmem1_ARID;
output  [31:0] m_axi_gmem1_ARLEN;
output  [2:0] m_axi_gmem1_ARSIZE;
output  [1:0] m_axi_gmem1_ARBURST;
output  [1:0] m_axi_gmem1_ARLOCK;
output  [3:0] m_axi_gmem1_ARCACHE;
output  [2:0] m_axi_gmem1_ARPROT;
output  [3:0] m_axi_gmem1_ARQOS;
output  [3:0] m_axi_gmem1_ARREGION;
output  [0:0] m_axi_gmem1_ARUSER;
input   m_axi_gmem1_RVALID;
output   m_axi_gmem1_RREADY;
input  [511:0] m_axi_gmem1_RDATA;
input   m_axi_gmem1_RLAST;
input  [0:0] m_axi_gmem1_RID;
input  [0:0] m_axi_gmem1_RUSER;
input  [1:0] m_axi_gmem1_RRESP;
input   m_axi_gmem1_BVALID;
output   m_axi_gmem1_BREADY;
input  [1:0] m_axi_gmem1_BRESP;
input  [0:0] m_axi_gmem1_BID;
input  [0:0] m_axi_gmem1_BUSER;
output   m_axi_gmem2_AWVALID;
input   m_axi_gmem2_AWREADY;
output  [63:0] m_axi_gmem2_AWADDR;
output  [0:0] m_axi_gmem2_AWID;
output  [31:0] m_axi_gmem2_AWLEN;
output  [2:0] m_axi_gmem2_AWSIZE;
output  [1:0] m_axi_gmem2_AWBURST;
output  [1:0] m_axi_gmem2_AWLOCK;
output  [3:0] m_axi_gmem2_AWCACHE;
output  [2:0] m_axi_gmem2_AWPROT;
output  [3:0] m_axi_gmem2_AWQOS;
output  [3:0] m_axi_gmem2_AWREGION;
output  [0:0] m_axi_gmem2_AWUSER;
output   m_axi_gmem2_WVALID;
input   m_axi_gmem2_WREADY;
output  [511:0] m_axi_gmem2_WDATA;
output  [63:0] m_axi_gmem2_WSTRB;
output   m_axi_gmem2_WLAST;
output  [0:0] m_axi_gmem2_WID;
output  [0:0] m_axi_gmem2_WUSER;
output   m_axi_gmem2_ARVALID;
input   m_axi_gmem2_ARREADY;
output  [63:0] m_axi_gmem2_ARADDR;
output  [0:0] m_axi_gmem2_ARID;
output  [31:0] m_axi_gmem2_ARLEN;
output  [2:0] m_axi_gmem2_ARSIZE;
output  [1:0] m_axi_gmem2_ARBURST;
output  [1:0] m_axi_gmem2_ARLOCK;
output  [3:0] m_axi_gmem2_ARCACHE;
output  [2:0] m_axi_gmem2_ARPROT;
output  [3:0] m_axi_gmem2_ARQOS;
output  [3:0] m_axi_gmem2_ARREGION;
output  [0:0] m_axi_gmem2_ARUSER;
input   m_axi_gmem2_RVALID;
output   m_axi_gmem2_RREADY;
input  [511:0] m_axi_gmem2_RDATA;
input   m_axi_gmem2_RLAST;
input  [0:0] m_axi_gmem2_RID;
input  [0:0] m_axi_gmem2_RUSER;
input  [1:0] m_axi_gmem2_RRESP;
input   m_axi_gmem2_BVALID;
output   m_axi_gmem2_BREADY;
input  [1:0] m_axi_gmem2_BRESP;
input  [0:0] m_axi_gmem2_BID;
input  [0:0] m_axi_gmem2_BUSER;
input  [63:0] block_r;
input  [63:0] q;
input  [63:0] voutp;
input  [31:0] ignore_dc;
input  [31:0] blocks;
input   ap_clk;
input   ap_rst;
input   block_r_ap_vld;
input   q_ap_vld;
input   voutp_ap_vld;
input   ignore_dc_ap_vld;
input   blocks_ap_vld;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;
output   ap_ext_blocking_n;
output   ap_str_blocking_n;
output   ap_int_blocking_n;

wire    krnl_idct_dataflow_entry6_U0_ap_start;
wire    krnl_idct_dataflow_entry6_U0_start_full_n;
wire    krnl_idct_dataflow_entry6_U0_ap_done;
wire    krnl_idct_dataflow_entry6_U0_ap_continue;
wire    krnl_idct_dataflow_entry6_U0_ap_idle;
wire    krnl_idct_dataflow_entry6_U0_ap_ready;
wire    krnl_idct_dataflow_entry6_U0_start_out;
wire    krnl_idct_dataflow_entry6_U0_start_write;
wire   [63:0] krnl_idct_dataflow_entry6_U0_block_out_din;
wire    krnl_idct_dataflow_entry6_U0_block_out_write;
wire   [63:0] krnl_idct_dataflow_entry6_U0_q_out_din;
wire    krnl_idct_dataflow_entry6_U0_q_out_write;
wire   [63:0] krnl_idct_dataflow_entry6_U0_voutp_out_din;
wire    krnl_idct_dataflow_entry6_U0_voutp_out_write;
wire   [31:0] krnl_idct_dataflow_entry6_U0_ignore_dc_out_din;
wire    krnl_idct_dataflow_entry6_U0_ignore_dc_out_write;
wire   [30:0] krnl_idct_dataflow_entry6_U0_blocks_out_din;
wire    krnl_idct_dataflow_entry6_U0_blocks_out_write;
wire   [31:0] krnl_idct_dataflow_entry6_U0_blocks_out1_din;
wire    krnl_idct_dataflow_entry6_U0_blocks_out1_write;
wire    krnl_idct_dataflow_entry6_U0_ap_ext_blocking_n;
wire    krnl_idct_dataflow_entry6_U0_ap_str_blocking_n;
wire    krnl_idct_dataflow_entry6_U0_ap_int_blocking_n;
wire    read_blocks_ap_uint_512_U0_ap_start;
wire    read_blocks_ap_uint_512_U0_ap_done;
wire    read_blocks_ap_uint_512_U0_ap_continue;
wire    read_blocks_ap_uint_512_U0_ap_idle;
wire    read_blocks_ap_uint_512_U0_ap_ready;
wire    read_blocks_ap_uint_512_U0_m_axi_gmem1_AWVALID;
wire   [63:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_AWADDR;
wire   [0:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_AWID;
wire   [31:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_AWLEN;
wire   [2:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_AWSIZE;
wire   [1:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_AWBURST;
wire   [1:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_AWLOCK;
wire   [3:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_AWCACHE;
wire   [2:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_AWPROT;
wire   [3:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_AWQOS;
wire   [3:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_AWREGION;
wire   [0:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_AWUSER;
wire    read_blocks_ap_uint_512_U0_m_axi_gmem1_WVALID;
wire   [511:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_WDATA;
wire   [63:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_WSTRB;
wire    read_blocks_ap_uint_512_U0_m_axi_gmem1_WLAST;
wire   [0:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_WID;
wire   [0:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_WUSER;
wire    read_blocks_ap_uint_512_U0_m_axi_gmem1_ARVALID;
wire   [63:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_ARADDR;
wire   [0:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_ARID;
wire   [31:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_ARLEN;
wire   [2:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_ARSIZE;
wire   [1:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_ARBURST;
wire   [1:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_ARLOCK;
wire   [3:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_ARCACHE;
wire   [2:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_ARPROT;
wire   [3:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_ARQOS;
wire   [3:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_ARREGION;
wire   [0:0] read_blocks_ap_uint_512_U0_m_axi_gmem1_ARUSER;
wire    read_blocks_ap_uint_512_U0_m_axi_gmem1_RREADY;
wire    read_blocks_ap_uint_512_U0_m_axi_gmem1_BREADY;
wire   [511:0] read_blocks_ap_uint_512_U0_iq4_din;
wire    read_blocks_ap_uint_512_U0_iq4_write;
wire    read_blocks_ap_uint_512_U0_in_r_read;
wire    read_blocks_ap_uint_512_U0_ap_ext_blocking_n;
wire    read_blocks_ap_uint_512_U0_ap_str_blocking_n;
wire    read_blocks_ap_uint_512_U0_ap_int_blocking_n;
wire    read_blocks_ap_int_512_U0_ap_start;
wire    read_blocks_ap_int_512_U0_ap_done;
wire    read_blocks_ap_int_512_U0_ap_continue;
wire    read_blocks_ap_int_512_U0_ap_idle;
wire    read_blocks_ap_int_512_U0_ap_ready;
wire    read_blocks_ap_int_512_U0_m_axi_gmem0_AWVALID;
wire   [63:0] read_blocks_ap_int_512_U0_m_axi_gmem0_AWADDR;
wire   [0:0] read_blocks_ap_int_512_U0_m_axi_gmem0_AWID;
wire   [31:0] read_blocks_ap_int_512_U0_m_axi_gmem0_AWLEN;
wire   [2:0] read_blocks_ap_int_512_U0_m_axi_gmem0_AWSIZE;
wire   [1:0] read_blocks_ap_int_512_U0_m_axi_gmem0_AWBURST;
wire   [1:0] read_blocks_ap_int_512_U0_m_axi_gmem0_AWLOCK;
wire   [3:0] read_blocks_ap_int_512_U0_m_axi_gmem0_AWCACHE;
wire   [2:0] read_blocks_ap_int_512_U0_m_axi_gmem0_AWPROT;
wire   [3:0] read_blocks_ap_int_512_U0_m_axi_gmem0_AWQOS;
wire   [3:0] read_blocks_ap_int_512_U0_m_axi_gmem0_AWREGION;
wire   [0:0] read_blocks_ap_int_512_U0_m_axi_gmem0_AWUSER;
wire    read_blocks_ap_int_512_U0_m_axi_gmem0_WVALID;
wire   [511:0] read_blocks_ap_int_512_U0_m_axi_gmem0_WDATA;
wire   [63:0] read_blocks_ap_int_512_U0_m_axi_gmem0_WSTRB;
wire    read_blocks_ap_int_512_U0_m_axi_gmem0_WLAST;
wire   [0:0] read_blocks_ap_int_512_U0_m_axi_gmem0_WID;
wire   [0:0] read_blocks_ap_int_512_U0_m_axi_gmem0_WUSER;
wire    read_blocks_ap_int_512_U0_m_axi_gmem0_ARVALID;
wire   [63:0] read_blocks_ap_int_512_U0_m_axi_gmem0_ARADDR;
wire   [0:0] read_blocks_ap_int_512_U0_m_axi_gmem0_ARID;
wire   [31:0] read_blocks_ap_int_512_U0_m_axi_gmem0_ARLEN;
wire   [2:0] read_blocks_ap_int_512_U0_m_axi_gmem0_ARSIZE;
wire   [1:0] read_blocks_ap_int_512_U0_m_axi_gmem0_ARBURST;
wire   [1:0] read_blocks_ap_int_512_U0_m_axi_gmem0_ARLOCK;
wire   [3:0] read_blocks_ap_int_512_U0_m_axi_gmem0_ARCACHE;
wire   [2:0] read_blocks_ap_int_512_U0_m_axi_gmem0_ARPROT;
wire   [3:0] read_blocks_ap_int_512_U0_m_axi_gmem0_ARQOS;
wire   [3:0] read_blocks_ap_int_512_U0_m_axi_gmem0_ARREGION;
wire   [0:0] read_blocks_ap_int_512_U0_m_axi_gmem0_ARUSER;
wire    read_blocks_ap_int_512_U0_m_axi_gmem0_RREADY;
wire    read_blocks_ap_int_512_U0_m_axi_gmem0_BREADY;
wire   [511:0] read_blocks_ap_int_512_U0_out_r_din;
wire    read_blocks_ap_int_512_U0_out_r_write;
wire    read_blocks_ap_int_512_U0_block_r_read;
wire    read_blocks_ap_int_512_U0_blocks_read;
wire    read_blocks_ap_int_512_U0_ap_ext_blocking_n;
wire    read_blocks_ap_int_512_U0_ap_str_blocking_n;
wire    read_blocks_ap_int_512_U0_ap_int_blocking_n;
wire    krnl_idct_dataflow_Block_split25_proc_U0_ap_start;
wire    krnl_idct_dataflow_Block_split25_proc_U0_ap_done;
wire    krnl_idct_dataflow_Block_split25_proc_U0_ap_continue;
wire    krnl_idct_dataflow_Block_split25_proc_U0_ap_idle;
wire    krnl_idct_dataflow_Block_split25_proc_U0_ap_ready;
wire    krnl_idct_dataflow_Block_split25_proc_U0_ignore_dc_read;
wire   [0:0] krnl_idct_dataflow_Block_split25_proc_U0_ap_return;
wire    krnl_idct_dataflow_Block_split25_proc_U0_ap_ext_blocking_n;
wire    krnl_idct_dataflow_Block_split25_proc_U0_ap_str_blocking_n;
wire    krnl_idct_dataflow_Block_split25_proc_U0_ap_int_blocking_n;
wire    ap_channel_done_icmp_ln331_loc_channel;
wire    icmp_ln331_loc_channel_full_n;
wire    execute_U0_ap_start;
wire    execute_U0_ap_done;
wire    execute_U0_ap_continue;
wire    execute_U0_ap_idle;
wire    execute_U0_ap_ready;
wire    execute_U0_iblock_read;
wire    execute_U0_iq_read;
wire   [511:0] execute_U0_ivoutp_din;
wire    execute_U0_ivoutp_write;
wire    execute_U0_ignore_dc;
wire    execute_U0_blocks_read;
wire   [30:0] execute_U0_blocks_out_din;
wire    execute_U0_blocks_out_write;
wire    execute_U0_ap_ext_blocking_n;
wire    execute_U0_ap_str_blocking_n;
wire    execute_U0_ap_int_blocking_n;
wire    write_blocks_U0_ap_start;
wire    write_blocks_U0_ap_done;
wire    write_blocks_U0_ap_continue;
wire    write_blocks_U0_ap_idle;
wire    write_blocks_U0_ap_ready;
wire    write_blocks_U0_m_axi_gmem2_AWVALID;
wire   [63:0] write_blocks_U0_m_axi_gmem2_AWADDR;
wire   [0:0] write_blocks_U0_m_axi_gmem2_AWID;
wire   [31:0] write_blocks_U0_m_axi_gmem2_AWLEN;
wire   [2:0] write_blocks_U0_m_axi_gmem2_AWSIZE;
wire   [1:0] write_blocks_U0_m_axi_gmem2_AWBURST;
wire   [1:0] write_blocks_U0_m_axi_gmem2_AWLOCK;
wire   [3:0] write_blocks_U0_m_axi_gmem2_AWCACHE;
wire   [2:0] write_blocks_U0_m_axi_gmem2_AWPROT;
wire   [3:0] write_blocks_U0_m_axi_gmem2_AWQOS;
wire   [3:0] write_blocks_U0_m_axi_gmem2_AWREGION;
wire   [0:0] write_blocks_U0_m_axi_gmem2_AWUSER;
wire    write_blocks_U0_m_axi_gmem2_WVALID;
wire   [511:0] write_blocks_U0_m_axi_gmem2_WDATA;
wire   [63:0] write_blocks_U0_m_axi_gmem2_WSTRB;
wire    write_blocks_U0_m_axi_gmem2_WLAST;
wire   [0:0] write_blocks_U0_m_axi_gmem2_WID;
wire   [0:0] write_blocks_U0_m_axi_gmem2_WUSER;
wire    write_blocks_U0_m_axi_gmem2_ARVALID;
wire   [63:0] write_blocks_U0_m_axi_gmem2_ARADDR;
wire   [0:0] write_blocks_U0_m_axi_gmem2_ARID;
wire   [31:0] write_blocks_U0_m_axi_gmem2_ARLEN;
wire   [2:0] write_blocks_U0_m_axi_gmem2_ARSIZE;
wire   [1:0] write_blocks_U0_m_axi_gmem2_ARBURST;
wire   [1:0] write_blocks_U0_m_axi_gmem2_ARLOCK;
wire   [3:0] write_blocks_U0_m_axi_gmem2_ARCACHE;
wire   [2:0] write_blocks_U0_m_axi_gmem2_ARPROT;
wire   [3:0] write_blocks_U0_m_axi_gmem2_ARQOS;
wire   [3:0] write_blocks_U0_m_axi_gmem2_ARREGION;
wire   [0:0] write_blocks_U0_m_axi_gmem2_ARUSER;
wire    write_blocks_U0_m_axi_gmem2_RREADY;
wire    write_blocks_U0_m_axi_gmem2_BREADY;
wire    write_blocks_U0_in_r_read;
wire    write_blocks_U0_voutp_read;
wire    write_blocks_U0_blocks_read;
wire    write_blocks_U0_ap_ext_blocking_n;
wire    write_blocks_U0_ap_str_blocking_n;
wire    write_blocks_U0_ap_int_blocking_n;
wire    ap_sync_continue;
wire    block_c_full_n;
wire   [63:0] block_c_dout;
wire    block_c_empty_n;
wire    q_c_full_n;
wire   [63:0] q_c_dout;
wire    q_c_empty_n;
wire    voutp_c_full_n;
wire   [63:0] voutp_c_dout;
wire    voutp_c_empty_n;
wire    ignore_dc_c_full_n;
wire   [31:0] ignore_dc_c_dout;
wire    ignore_dc_c_empty_n;
wire    blocks_c_full_n;
wire   [30:0] blocks_c_dout;
wire    blocks_c_empty_n;
wire    blocks_c13_full_n;
wire   [31:0] blocks_c13_dout;
wire    blocks_c13_empty_n;
wire    iq_full_n;
wire   [511:0] iq_dout;
wire    iq_empty_n;
wire    iblock_full_n;
wire   [511:0] iblock_dout;
wire    iblock_empty_n;
wire   [0:0] icmp_ln331_loc_channel_dout;
wire    icmp_ln331_loc_channel_empty_n;
wire    ivoutp_full_n;
wire   [511:0] ivoutp_dout;
wire    ivoutp_empty_n;
wire    blocks_c14_full_n;
wire   [30:0] blocks_c14_dout;
wire    blocks_c14_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_krnl_idct_dataflow_entry6_U0_ap_ready;
wire    ap_sync_krnl_idct_dataflow_entry6_U0_ap_ready;
reg   [1:0] krnl_idct_dataflow_entry6_U0_ap_ready_count;
reg    ap_sync_reg_read_blocks_ap_uint_512_U0_ap_ready;
wire    ap_sync_read_blocks_ap_uint_512_U0_ap_ready;
reg   [1:0] read_blocks_ap_uint_512_U0_ap_ready_count;
reg    ap_sync_reg_read_blocks_ap_int_512_U0_ap_ready;
wire    ap_sync_read_blocks_ap_int_512_U0_ap_ready;
reg   [1:0] read_blocks_ap_int_512_U0_ap_ready_count;
wire   [0:0] start_for_krnl_idct_dataflow_Block_split25_proc_U0_din;
wire    start_for_krnl_idct_dataflow_Block_split25_proc_U0_full_n;
wire   [0:0] start_for_krnl_idct_dataflow_Block_split25_proc_U0_dout;
wire    start_for_krnl_idct_dataflow_Block_split25_proc_U0_empty_n;
wire   [0:0] start_for_write_blocks_U0_din;
wire    start_for_write_blocks_U0_full_n;
wire   [0:0] start_for_write_blocks_U0_dout;
wire    start_for_write_blocks_U0_empty_n;
wire    read_blocks_ap_uint_512_U0_start_full_n;
wire    read_blocks_ap_uint_512_U0_start_write;
wire    read_blocks_ap_int_512_U0_start_full_n;
wire    read_blocks_ap_int_512_U0_start_write;
wire    krnl_idct_dataflow_Block_split25_proc_U0_start_full_n;
wire    krnl_idct_dataflow_Block_split25_proc_U0_start_write;
wire    execute_U0_start_full_n;
wire    execute_U0_start_write;
wire    write_blocks_U0_start_full_n;
wire    write_blocks_U0_start_write;
wire    ap_ext_blocking_cur_n;
wire    ap_str_blocking_cur_n;
wire    ap_int_blocking_cur_n;
wire    ap_ext_blocking_sub_n;
wire    ap_str_blocking_sub_n;
wire    ap_int_blocking_sub_n;

// power-on initialization
initial begin
#0 ap_sync_reg_krnl_idct_dataflow_entry6_U0_ap_ready = 1'b0;
#0 krnl_idct_dataflow_entry6_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_read_blocks_ap_uint_512_U0_ap_ready = 1'b0;
#0 read_blocks_ap_uint_512_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_read_blocks_ap_int_512_U0_ap_ready = 1'b0;
#0 read_blocks_ap_int_512_U0_ap_ready_count = 2'd0;
end

krnl_idct_krnl_idct_dataflow_entry6 krnl_idct_dataflow_entry6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(krnl_idct_dataflow_entry6_U0_ap_start),
    .start_full_n(krnl_idct_dataflow_entry6_U0_start_full_n),
    .ap_done(krnl_idct_dataflow_entry6_U0_ap_done),
    .ap_continue(krnl_idct_dataflow_entry6_U0_ap_continue),
    .ap_idle(krnl_idct_dataflow_entry6_U0_ap_idle),
    .ap_ready(krnl_idct_dataflow_entry6_U0_ap_ready),
    .start_out(krnl_idct_dataflow_entry6_U0_start_out),
    .start_write(krnl_idct_dataflow_entry6_U0_start_write),
    .block_r(block_r),
    .q(q),
    .voutp(voutp),
    .ignore_dc(ignore_dc),
    .blocks(blocks),
    .block_out_din(krnl_idct_dataflow_entry6_U0_block_out_din),
    .block_out_full_n(block_c_full_n),
    .block_out_write(krnl_idct_dataflow_entry6_U0_block_out_write),
    .q_out_din(krnl_idct_dataflow_entry6_U0_q_out_din),
    .q_out_full_n(q_c_full_n),
    .q_out_write(krnl_idct_dataflow_entry6_U0_q_out_write),
    .voutp_out_din(krnl_idct_dataflow_entry6_U0_voutp_out_din),
    .voutp_out_full_n(voutp_c_full_n),
    .voutp_out_write(krnl_idct_dataflow_entry6_U0_voutp_out_write),
    .ignore_dc_out_din(krnl_idct_dataflow_entry6_U0_ignore_dc_out_din),
    .ignore_dc_out_full_n(ignore_dc_c_full_n),
    .ignore_dc_out_write(krnl_idct_dataflow_entry6_U0_ignore_dc_out_write),
    .blocks_out_din(krnl_idct_dataflow_entry6_U0_blocks_out_din),
    .blocks_out_full_n(blocks_c_full_n),
    .blocks_out_write(krnl_idct_dataflow_entry6_U0_blocks_out_write),
    .blocks_out1_din(krnl_idct_dataflow_entry6_U0_blocks_out1_din),
    .blocks_out1_full_n(blocks_c13_full_n),
    .blocks_out1_write(krnl_idct_dataflow_entry6_U0_blocks_out1_write),
    .ap_ext_blocking_n(krnl_idct_dataflow_entry6_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(krnl_idct_dataflow_entry6_U0_ap_str_blocking_n),
    .ap_int_blocking_n(krnl_idct_dataflow_entry6_U0_ap_int_blocking_n)
);

krnl_idct_read_blocks_ap_uint_512_s read_blocks_ap_uint_512_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(read_blocks_ap_uint_512_U0_ap_start),
    .ap_done(read_blocks_ap_uint_512_U0_ap_done),
    .ap_continue(read_blocks_ap_uint_512_U0_ap_continue),
    .ap_idle(read_blocks_ap_uint_512_U0_ap_idle),
    .ap_ready(read_blocks_ap_uint_512_U0_ap_ready),
    .m_axi_gmem1_AWVALID(read_blocks_ap_uint_512_U0_m_axi_gmem1_AWVALID),
    .m_axi_gmem1_AWREADY(1'b0),
    .m_axi_gmem1_AWADDR(read_blocks_ap_uint_512_U0_m_axi_gmem1_AWADDR),
    .m_axi_gmem1_AWID(read_blocks_ap_uint_512_U0_m_axi_gmem1_AWID),
    .m_axi_gmem1_AWLEN(read_blocks_ap_uint_512_U0_m_axi_gmem1_AWLEN),
    .m_axi_gmem1_AWSIZE(read_blocks_ap_uint_512_U0_m_axi_gmem1_AWSIZE),
    .m_axi_gmem1_AWBURST(read_blocks_ap_uint_512_U0_m_axi_gmem1_AWBURST),
    .m_axi_gmem1_AWLOCK(read_blocks_ap_uint_512_U0_m_axi_gmem1_AWLOCK),
    .m_axi_gmem1_AWCACHE(read_blocks_ap_uint_512_U0_m_axi_gmem1_AWCACHE),
    .m_axi_gmem1_AWPROT(read_blocks_ap_uint_512_U0_m_axi_gmem1_AWPROT),
    .m_axi_gmem1_AWQOS(read_blocks_ap_uint_512_U0_m_axi_gmem1_AWQOS),
    .m_axi_gmem1_AWREGION(read_blocks_ap_uint_512_U0_m_axi_gmem1_AWREGION),
    .m_axi_gmem1_AWUSER(read_blocks_ap_uint_512_U0_m_axi_gmem1_AWUSER),
    .m_axi_gmem1_WVALID(read_blocks_ap_uint_512_U0_m_axi_gmem1_WVALID),
    .m_axi_gmem1_WREADY(1'b0),
    .m_axi_gmem1_WDATA(read_blocks_ap_uint_512_U0_m_axi_gmem1_WDATA),
    .m_axi_gmem1_WSTRB(read_blocks_ap_uint_512_U0_m_axi_gmem1_WSTRB),
    .m_axi_gmem1_WLAST(read_blocks_ap_uint_512_U0_m_axi_gmem1_WLAST),
    .m_axi_gmem1_WID(read_blocks_ap_uint_512_U0_m_axi_gmem1_WID),
    .m_axi_gmem1_WUSER(read_blocks_ap_uint_512_U0_m_axi_gmem1_WUSER),
    .m_axi_gmem1_ARVALID(read_blocks_ap_uint_512_U0_m_axi_gmem1_ARVALID),
    .m_axi_gmem1_ARREADY(m_axi_gmem1_ARREADY),
    .m_axi_gmem1_ARADDR(read_blocks_ap_uint_512_U0_m_axi_gmem1_ARADDR),
    .m_axi_gmem1_ARID(read_blocks_ap_uint_512_U0_m_axi_gmem1_ARID),
    .m_axi_gmem1_ARLEN(read_blocks_ap_uint_512_U0_m_axi_gmem1_ARLEN),
    .m_axi_gmem1_ARSIZE(read_blocks_ap_uint_512_U0_m_axi_gmem1_ARSIZE),
    .m_axi_gmem1_ARBURST(read_blocks_ap_uint_512_U0_m_axi_gmem1_ARBURST),
    .m_axi_gmem1_ARLOCK(read_blocks_ap_uint_512_U0_m_axi_gmem1_ARLOCK),
    .m_axi_gmem1_ARCACHE(read_blocks_ap_uint_512_U0_m_axi_gmem1_ARCACHE),
    .m_axi_gmem1_ARPROT(read_blocks_ap_uint_512_U0_m_axi_gmem1_ARPROT),
    .m_axi_gmem1_ARQOS(read_blocks_ap_uint_512_U0_m_axi_gmem1_ARQOS),
    .m_axi_gmem1_ARREGION(read_blocks_ap_uint_512_U0_m_axi_gmem1_ARREGION),
    .m_axi_gmem1_ARUSER(read_blocks_ap_uint_512_U0_m_axi_gmem1_ARUSER),
    .m_axi_gmem1_RVALID(m_axi_gmem1_RVALID),
    .m_axi_gmem1_RREADY(read_blocks_ap_uint_512_U0_m_axi_gmem1_RREADY),
    .m_axi_gmem1_RDATA(m_axi_gmem1_RDATA),
    .m_axi_gmem1_RLAST(m_axi_gmem1_RLAST),
    .m_axi_gmem1_RID(m_axi_gmem1_RID),
    .m_axi_gmem1_RUSER(m_axi_gmem1_RUSER),
    .m_axi_gmem1_RRESP(m_axi_gmem1_RRESP),
    .m_axi_gmem1_BVALID(1'b0),
    .m_axi_gmem1_BREADY(read_blocks_ap_uint_512_U0_m_axi_gmem1_BREADY),
    .m_axi_gmem1_BRESP(2'd0),
    .m_axi_gmem1_BID(1'd0),
    .m_axi_gmem1_BUSER(1'd0),
    .iq4_din(read_blocks_ap_uint_512_U0_iq4_din),
    .iq4_full_n(iq_full_n),
    .iq4_write(read_blocks_ap_uint_512_U0_iq4_write),
    .in_r_dout(q_c_dout),
    .in_r_empty_n(q_c_empty_n),
    .in_r_read(read_blocks_ap_uint_512_U0_in_r_read),
    .ap_ext_blocking_n(read_blocks_ap_uint_512_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(read_blocks_ap_uint_512_U0_ap_str_blocking_n),
    .ap_int_blocking_n(read_blocks_ap_uint_512_U0_ap_int_blocking_n)
);

krnl_idct_read_blocks_ap_int_512_s read_blocks_ap_int_512_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(read_blocks_ap_int_512_U0_ap_start),
    .ap_done(read_blocks_ap_int_512_U0_ap_done),
    .ap_continue(read_blocks_ap_int_512_U0_ap_continue),
    .ap_idle(read_blocks_ap_int_512_U0_ap_idle),
    .ap_ready(read_blocks_ap_int_512_U0_ap_ready),
    .m_axi_gmem0_AWVALID(read_blocks_ap_int_512_U0_m_axi_gmem0_AWVALID),
    .m_axi_gmem0_AWREADY(1'b0),
    .m_axi_gmem0_AWADDR(read_blocks_ap_int_512_U0_m_axi_gmem0_AWADDR),
    .m_axi_gmem0_AWID(read_blocks_ap_int_512_U0_m_axi_gmem0_AWID),
    .m_axi_gmem0_AWLEN(read_blocks_ap_int_512_U0_m_axi_gmem0_AWLEN),
    .m_axi_gmem0_AWSIZE(read_blocks_ap_int_512_U0_m_axi_gmem0_AWSIZE),
    .m_axi_gmem0_AWBURST(read_blocks_ap_int_512_U0_m_axi_gmem0_AWBURST),
    .m_axi_gmem0_AWLOCK(read_blocks_ap_int_512_U0_m_axi_gmem0_AWLOCK),
    .m_axi_gmem0_AWCACHE(read_blocks_ap_int_512_U0_m_axi_gmem0_AWCACHE),
    .m_axi_gmem0_AWPROT(read_blocks_ap_int_512_U0_m_axi_gmem0_AWPROT),
    .m_axi_gmem0_AWQOS(read_blocks_ap_int_512_U0_m_axi_gmem0_AWQOS),
    .m_axi_gmem0_AWREGION(read_blocks_ap_int_512_U0_m_axi_gmem0_AWREGION),
    .m_axi_gmem0_AWUSER(read_blocks_ap_int_512_U0_m_axi_gmem0_AWUSER),
    .m_axi_gmem0_WVALID(read_blocks_ap_int_512_U0_m_axi_gmem0_WVALID),
    .m_axi_gmem0_WREADY(1'b0),
    .m_axi_gmem0_WDATA(read_blocks_ap_int_512_U0_m_axi_gmem0_WDATA),
    .m_axi_gmem0_WSTRB(read_blocks_ap_int_512_U0_m_axi_gmem0_WSTRB),
    .m_axi_gmem0_WLAST(read_blocks_ap_int_512_U0_m_axi_gmem0_WLAST),
    .m_axi_gmem0_WID(read_blocks_ap_int_512_U0_m_axi_gmem0_WID),
    .m_axi_gmem0_WUSER(read_blocks_ap_int_512_U0_m_axi_gmem0_WUSER),
    .m_axi_gmem0_ARVALID(read_blocks_ap_int_512_U0_m_axi_gmem0_ARVALID),
    .m_axi_gmem0_ARREADY(m_axi_gmem0_ARREADY),
    .m_axi_gmem0_ARADDR(read_blocks_ap_int_512_U0_m_axi_gmem0_ARADDR),
    .m_axi_gmem0_ARID(read_blocks_ap_int_512_U0_m_axi_gmem0_ARID),
    .m_axi_gmem0_ARLEN(read_blocks_ap_int_512_U0_m_axi_gmem0_ARLEN),
    .m_axi_gmem0_ARSIZE(read_blocks_ap_int_512_U0_m_axi_gmem0_ARSIZE),
    .m_axi_gmem0_ARBURST(read_blocks_ap_int_512_U0_m_axi_gmem0_ARBURST),
    .m_axi_gmem0_ARLOCK(read_blocks_ap_int_512_U0_m_axi_gmem0_ARLOCK),
    .m_axi_gmem0_ARCACHE(read_blocks_ap_int_512_U0_m_axi_gmem0_ARCACHE),
    .m_axi_gmem0_ARPROT(read_blocks_ap_int_512_U0_m_axi_gmem0_ARPROT),
    .m_axi_gmem0_ARQOS(read_blocks_ap_int_512_U0_m_axi_gmem0_ARQOS),
    .m_axi_gmem0_ARREGION(read_blocks_ap_int_512_U0_m_axi_gmem0_ARREGION),
    .m_axi_gmem0_ARUSER(read_blocks_ap_int_512_U0_m_axi_gmem0_ARUSER),
    .m_axi_gmem0_RVALID(m_axi_gmem0_RVALID),
    .m_axi_gmem0_RREADY(read_blocks_ap_int_512_U0_m_axi_gmem0_RREADY),
    .m_axi_gmem0_RDATA(m_axi_gmem0_RDATA),
    .m_axi_gmem0_RLAST(m_axi_gmem0_RLAST),
    .m_axi_gmem0_RID(m_axi_gmem0_RID),
    .m_axi_gmem0_RUSER(m_axi_gmem0_RUSER),
    .m_axi_gmem0_RRESP(m_axi_gmem0_RRESP),
    .m_axi_gmem0_BVALID(1'b0),
    .m_axi_gmem0_BREADY(read_blocks_ap_int_512_U0_m_axi_gmem0_BREADY),
    .m_axi_gmem0_BRESP(2'd0),
    .m_axi_gmem0_BID(1'd0),
    .m_axi_gmem0_BUSER(1'd0),
    .out_r_din(read_blocks_ap_int_512_U0_out_r_din),
    .out_r_full_n(iblock_full_n),
    .out_r_write(read_blocks_ap_int_512_U0_out_r_write),
    .block_r_dout(block_c_dout),
    .block_r_empty_n(block_c_empty_n),
    .block_r_read(read_blocks_ap_int_512_U0_block_r_read),
    .blocks_dout(blocks_c_dout),
    .blocks_empty_n(blocks_c_empty_n),
    .blocks_read(read_blocks_ap_int_512_U0_blocks_read),
    .ap_ext_blocking_n(read_blocks_ap_int_512_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(read_blocks_ap_int_512_U0_ap_str_blocking_n),
    .ap_int_blocking_n(read_blocks_ap_int_512_U0_ap_int_blocking_n)
);

krnl_idct_krnl_idct_dataflow_Block_split25_proc krnl_idct_dataflow_Block_split25_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(krnl_idct_dataflow_Block_split25_proc_U0_ap_start),
    .ap_done(krnl_idct_dataflow_Block_split25_proc_U0_ap_done),
    .ap_continue(krnl_idct_dataflow_Block_split25_proc_U0_ap_continue),
    .ap_idle(krnl_idct_dataflow_Block_split25_proc_U0_ap_idle),
    .ap_ready(krnl_idct_dataflow_Block_split25_proc_U0_ap_ready),
    .ignore_dc_dout(ignore_dc_c_dout),
    .ignore_dc_empty_n(ignore_dc_c_empty_n),
    .ignore_dc_read(krnl_idct_dataflow_Block_split25_proc_U0_ignore_dc_read),
    .ap_return(krnl_idct_dataflow_Block_split25_proc_U0_ap_return),
    .ap_ext_blocking_n(krnl_idct_dataflow_Block_split25_proc_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(krnl_idct_dataflow_Block_split25_proc_U0_ap_str_blocking_n),
    .ap_int_blocking_n(krnl_idct_dataflow_Block_split25_proc_U0_ap_int_blocking_n)
);

krnl_idct_execute execute_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(execute_U0_ap_start),
    .ap_done(execute_U0_ap_done),
    .ap_continue(execute_U0_ap_continue),
    .ap_idle(execute_U0_ap_idle),
    .ap_ready(execute_U0_ap_ready),
    .iblock_dout(iblock_dout),
    .iblock_empty_n(iblock_empty_n),
    .iblock_read(execute_U0_iblock_read),
    .iq_dout(iq_dout),
    .iq_empty_n(iq_empty_n),
    .iq_read(execute_U0_iq_read),
    .ivoutp_din(execute_U0_ivoutp_din),
    .ivoutp_full_n(ivoutp_full_n),
    .ivoutp_write(execute_U0_ivoutp_write),
    .ignore_dc(execute_U0_ignore_dc),
    .blocks_dout(blocks_c13_dout),
    .blocks_empty_n(blocks_c13_empty_n),
    .blocks_read(execute_U0_blocks_read),
    .blocks_out_din(execute_U0_blocks_out_din),
    .blocks_out_full_n(blocks_c14_full_n),
    .blocks_out_write(execute_U0_blocks_out_write),
    .ap_ext_blocking_n(execute_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(execute_U0_ap_str_blocking_n),
    .ap_int_blocking_n(execute_U0_ap_int_blocking_n)
);

krnl_idct_write_blocks write_blocks_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(write_blocks_U0_ap_start),
    .ap_done(write_blocks_U0_ap_done),
    .ap_continue(write_blocks_U0_ap_continue),
    .ap_idle(write_blocks_U0_ap_idle),
    .ap_ready(write_blocks_U0_ap_ready),
    .m_axi_gmem2_AWVALID(write_blocks_U0_m_axi_gmem2_AWVALID),
    .m_axi_gmem2_AWREADY(m_axi_gmem2_AWREADY),
    .m_axi_gmem2_AWADDR(write_blocks_U0_m_axi_gmem2_AWADDR),
    .m_axi_gmem2_AWID(write_blocks_U0_m_axi_gmem2_AWID),
    .m_axi_gmem2_AWLEN(write_blocks_U0_m_axi_gmem2_AWLEN),
    .m_axi_gmem2_AWSIZE(write_blocks_U0_m_axi_gmem2_AWSIZE),
    .m_axi_gmem2_AWBURST(write_blocks_U0_m_axi_gmem2_AWBURST),
    .m_axi_gmem2_AWLOCK(write_blocks_U0_m_axi_gmem2_AWLOCK),
    .m_axi_gmem2_AWCACHE(write_blocks_U0_m_axi_gmem2_AWCACHE),
    .m_axi_gmem2_AWPROT(write_blocks_U0_m_axi_gmem2_AWPROT),
    .m_axi_gmem2_AWQOS(write_blocks_U0_m_axi_gmem2_AWQOS),
    .m_axi_gmem2_AWREGION(write_blocks_U0_m_axi_gmem2_AWREGION),
    .m_axi_gmem2_AWUSER(write_blocks_U0_m_axi_gmem2_AWUSER),
    .m_axi_gmem2_WVALID(write_blocks_U0_m_axi_gmem2_WVALID),
    .m_axi_gmem2_WREADY(m_axi_gmem2_WREADY),
    .m_axi_gmem2_WDATA(write_blocks_U0_m_axi_gmem2_WDATA),
    .m_axi_gmem2_WSTRB(write_blocks_U0_m_axi_gmem2_WSTRB),
    .m_axi_gmem2_WLAST(write_blocks_U0_m_axi_gmem2_WLAST),
    .m_axi_gmem2_WID(write_blocks_U0_m_axi_gmem2_WID),
    .m_axi_gmem2_WUSER(write_blocks_U0_m_axi_gmem2_WUSER),
    .m_axi_gmem2_ARVALID(write_blocks_U0_m_axi_gmem2_ARVALID),
    .m_axi_gmem2_ARREADY(1'b0),
    .m_axi_gmem2_ARADDR(write_blocks_U0_m_axi_gmem2_ARADDR),
    .m_axi_gmem2_ARID(write_blocks_U0_m_axi_gmem2_ARID),
    .m_axi_gmem2_ARLEN(write_blocks_U0_m_axi_gmem2_ARLEN),
    .m_axi_gmem2_ARSIZE(write_blocks_U0_m_axi_gmem2_ARSIZE),
    .m_axi_gmem2_ARBURST(write_blocks_U0_m_axi_gmem2_ARBURST),
    .m_axi_gmem2_ARLOCK(write_blocks_U0_m_axi_gmem2_ARLOCK),
    .m_axi_gmem2_ARCACHE(write_blocks_U0_m_axi_gmem2_ARCACHE),
    .m_axi_gmem2_ARPROT(write_blocks_U0_m_axi_gmem2_ARPROT),
    .m_axi_gmem2_ARQOS(write_blocks_U0_m_axi_gmem2_ARQOS),
    .m_axi_gmem2_ARREGION(write_blocks_U0_m_axi_gmem2_ARREGION),
    .m_axi_gmem2_ARUSER(write_blocks_U0_m_axi_gmem2_ARUSER),
    .m_axi_gmem2_RVALID(1'b0),
    .m_axi_gmem2_RREADY(write_blocks_U0_m_axi_gmem2_RREADY),
    .m_axi_gmem2_RDATA(512'd0),
    .m_axi_gmem2_RLAST(1'b0),
    .m_axi_gmem2_RID(1'd0),
    .m_axi_gmem2_RUSER(1'd0),
    .m_axi_gmem2_RRESP(2'd0),
    .m_axi_gmem2_BVALID(m_axi_gmem2_BVALID),
    .m_axi_gmem2_BREADY(write_blocks_U0_m_axi_gmem2_BREADY),
    .m_axi_gmem2_BRESP(m_axi_gmem2_BRESP),
    .m_axi_gmem2_BID(m_axi_gmem2_BID),
    .m_axi_gmem2_BUSER(m_axi_gmem2_BUSER),
    .in_r_dout(ivoutp_dout),
    .in_r_empty_n(ivoutp_empty_n),
    .in_r_read(write_blocks_U0_in_r_read),
    .voutp_dout(voutp_c_dout),
    .voutp_empty_n(voutp_c_empty_n),
    .voutp_read(write_blocks_U0_voutp_read),
    .blocks_dout(blocks_c14_dout),
    .blocks_empty_n(blocks_c14_empty_n),
    .blocks_read(write_blocks_U0_blocks_read),
    .ap_ext_blocking_n(write_blocks_U0_ap_ext_blocking_n),
    .ap_str_blocking_n(write_blocks_U0_ap_str_blocking_n),
    .ap_int_blocking_n(write_blocks_U0_ap_int_blocking_n)
);

krnl_idct_fifo_w64_d2_S block_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(krnl_idct_dataflow_entry6_U0_block_out_din),
    .if_full_n(block_c_full_n),
    .if_write(krnl_idct_dataflow_entry6_U0_block_out_write),
    .if_dout(block_c_dout),
    .if_empty_n(block_c_empty_n),
    .if_read(read_blocks_ap_int_512_U0_block_r_read)
);

krnl_idct_fifo_w64_d2_S q_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(krnl_idct_dataflow_entry6_U0_q_out_din),
    .if_full_n(q_c_full_n),
    .if_write(krnl_idct_dataflow_entry6_U0_q_out_write),
    .if_dout(q_c_dout),
    .if_empty_n(q_c_empty_n),
    .if_read(read_blocks_ap_uint_512_U0_in_r_read)
);

krnl_idct_fifo_w64_d4_S voutp_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(krnl_idct_dataflow_entry6_U0_voutp_out_din),
    .if_full_n(voutp_c_full_n),
    .if_write(krnl_idct_dataflow_entry6_U0_voutp_out_write),
    .if_dout(voutp_c_dout),
    .if_empty_n(voutp_c_empty_n),
    .if_read(write_blocks_U0_voutp_read)
);

krnl_idct_fifo_w32_d2_S ignore_dc_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(krnl_idct_dataflow_entry6_U0_ignore_dc_out_din),
    .if_full_n(ignore_dc_c_full_n),
    .if_write(krnl_idct_dataflow_entry6_U0_ignore_dc_out_write),
    .if_dout(ignore_dc_c_dout),
    .if_empty_n(ignore_dc_c_empty_n),
    .if_read(krnl_idct_dataflow_Block_split25_proc_U0_ignore_dc_read)
);

krnl_idct_fifo_w31_d2_S blocks_c_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(krnl_idct_dataflow_entry6_U0_blocks_out_din),
    .if_full_n(blocks_c_full_n),
    .if_write(krnl_idct_dataflow_entry6_U0_blocks_out_write),
    .if_dout(blocks_c_dout),
    .if_empty_n(blocks_c_empty_n),
    .if_read(read_blocks_ap_int_512_U0_blocks_read)
);

krnl_idct_fifo_w32_d3_S blocks_c13_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(krnl_idct_dataflow_entry6_U0_blocks_out1_din),
    .if_full_n(blocks_c13_full_n),
    .if_write(krnl_idct_dataflow_entry6_U0_blocks_out1_write),
    .if_dout(blocks_c13_dout),
    .if_empty_n(blocks_c13_empty_n),
    .if_read(execute_U0_blocks_read)
);

krnl_idct_fifo_w512_d2_S iq_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_blocks_ap_uint_512_U0_iq4_din),
    .if_full_n(iq_full_n),
    .if_write(read_blocks_ap_uint_512_U0_iq4_write),
    .if_dout(iq_dout),
    .if_empty_n(iq_empty_n),
    .if_read(execute_U0_iq_read)
);

krnl_idct_fifo_w512_d512_A iblock_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_blocks_ap_int_512_U0_out_r_din),
    .if_full_n(iblock_full_n),
    .if_write(read_blocks_ap_int_512_U0_out_r_write),
    .if_dout(iblock_dout),
    .if_empty_n(iblock_empty_n),
    .if_read(execute_U0_iblock_read)
);

krnl_idct_fifo_w1_d2_S icmp_ln331_loc_channel_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(krnl_idct_dataflow_Block_split25_proc_U0_ap_return),
    .if_full_n(icmp_ln331_loc_channel_full_n),
    .if_write(krnl_idct_dataflow_Block_split25_proc_U0_ap_done),
    .if_dout(icmp_ln331_loc_channel_dout),
    .if_empty_n(icmp_ln331_loc_channel_empty_n),
    .if_read(execute_U0_ap_ready)
);

krnl_idct_fifo_w512_d512_A ivoutp_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(execute_U0_ivoutp_din),
    .if_full_n(ivoutp_full_n),
    .if_write(execute_U0_ivoutp_write),
    .if_dout(ivoutp_dout),
    .if_empty_n(ivoutp_empty_n),
    .if_read(write_blocks_U0_in_r_read)
);

krnl_idct_fifo_w31_d2_S blocks_c14_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(execute_U0_blocks_out_din),
    .if_full_n(blocks_c14_full_n),
    .if_write(execute_U0_blocks_out_write),
    .if_dout(blocks_c14_dout),
    .if_empty_n(blocks_c14_empty_n),
    .if_read(write_blocks_U0_blocks_read)
);

krnl_idct_start_for_krnl_idct_dataflow_Block_split25_proc_U0 start_for_krnl_idct_dataflow_Block_split25_proc_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_krnl_idct_dataflow_Block_split25_proc_U0_din),
    .if_full_n(start_for_krnl_idct_dataflow_Block_split25_proc_U0_full_n),
    .if_write(krnl_idct_dataflow_entry6_U0_start_write),
    .if_dout(start_for_krnl_idct_dataflow_Block_split25_proc_U0_dout),
    .if_empty_n(start_for_krnl_idct_dataflow_Block_split25_proc_U0_empty_n),
    .if_read(krnl_idct_dataflow_Block_split25_proc_U0_ap_ready)
);

krnl_idct_start_for_write_blocks_U0 start_for_write_blocks_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_write_blocks_U0_din),
    .if_full_n(start_for_write_blocks_U0_full_n),
    .if_write(krnl_idct_dataflow_entry6_U0_start_write),
    .if_dout(start_for_write_blocks_U0_dout),
    .if_empty_n(start_for_write_blocks_U0_empty_n),
    .if_read(write_blocks_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_krnl_idct_dataflow_entry6_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_krnl_idct_dataflow_entry6_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_krnl_idct_dataflow_entry6_U0_ap_ready <= ap_sync_krnl_idct_dataflow_entry6_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_read_blocks_ap_int_512_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_read_blocks_ap_int_512_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_read_blocks_ap_int_512_U0_ap_ready <= ap_sync_read_blocks_ap_int_512_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_sync_reg_read_blocks_ap_uint_512_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_read_blocks_ap_uint_512_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_read_blocks_ap_uint_512_U0_ap_ready <= ap_sync_read_blocks_ap_uint_512_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (krnl_idct_dataflow_entry6_U0_ap_ready == 1'b0))) begin
        krnl_idct_dataflow_entry6_U0_ap_ready_count <= (krnl_idct_dataflow_entry6_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (krnl_idct_dataflow_entry6_U0_ap_ready == 1'b1))) begin
        krnl_idct_dataflow_entry6_U0_ap_ready_count <= (krnl_idct_dataflow_entry6_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (read_blocks_ap_int_512_U0_ap_ready == 1'b0))) begin
        read_blocks_ap_int_512_U0_ap_ready_count <= (read_blocks_ap_int_512_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (read_blocks_ap_int_512_U0_ap_ready == 1'b1))) begin
        read_blocks_ap_int_512_U0_ap_ready_count <= (read_blocks_ap_int_512_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (read_blocks_ap_uint_512_U0_ap_ready == 1'b0))) begin
        read_blocks_ap_uint_512_U0_ap_ready_count <= (read_blocks_ap_uint_512_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (read_blocks_ap_uint_512_U0_ap_ready == 1'b1))) begin
        read_blocks_ap_uint_512_U0_ap_ready_count <= (read_blocks_ap_uint_512_U0_ap_ready_count + 2'd1);
    end
end

assign ap_channel_done_icmp_ln331_loc_channel = krnl_idct_dataflow_Block_split25_proc_U0_ap_done;

assign ap_done = write_blocks_U0_ap_done;

assign ap_ext_blocking_cur_n = 1'b1;

assign ap_ext_blocking_n = (ap_ext_blocking_sub_n & ap_ext_blocking_cur_n);

assign ap_ext_blocking_sub_n = (write_blocks_U0_ap_ext_blocking_n & read_blocks_ap_uint_512_U0_ap_ext_blocking_n & read_blocks_ap_int_512_U0_ap_ext_blocking_n & krnl_idct_dataflow_entry6_U0_ap_ext_blocking_n & krnl_idct_dataflow_Block_split25_proc_U0_ap_ext_blocking_n & execute_U0_ap_ext_blocking_n);

assign ap_idle = (write_blocks_U0_ap_idle & read_blocks_ap_uint_512_U0_ap_idle & read_blocks_ap_int_512_U0_ap_idle & krnl_idct_dataflow_entry6_U0_ap_idle & krnl_idct_dataflow_Block_split25_proc_U0_ap_idle & (icmp_ln331_loc_channel_empty_n ^ 1'b1) & execute_U0_ap_idle);

assign ap_int_blocking_cur_n = 1'b1;

assign ap_int_blocking_n = (ap_int_blocking_sub_n & ap_int_blocking_cur_n);

assign ap_int_blocking_sub_n = (write_blocks_U0_ap_int_blocking_n & read_blocks_ap_uint_512_U0_ap_int_blocking_n & read_blocks_ap_int_512_U0_ap_int_blocking_n & krnl_idct_dataflow_entry6_U0_ap_int_blocking_n & krnl_idct_dataflow_Block_split25_proc_U0_ap_int_blocking_n & execute_U0_ap_int_blocking_n);

assign ap_ready = ap_sync_ready;

assign ap_str_blocking_cur_n = 1'b1;

assign ap_str_blocking_n = (ap_str_blocking_sub_n & ap_str_blocking_cur_n);

assign ap_str_blocking_sub_n = (write_blocks_U0_ap_str_blocking_n & read_blocks_ap_uint_512_U0_ap_str_blocking_n & read_blocks_ap_int_512_U0_ap_str_blocking_n & krnl_idct_dataflow_entry6_U0_ap_str_blocking_n & krnl_idct_dataflow_Block_split25_proc_U0_ap_str_blocking_n & execute_U0_ap_str_blocking_n);

assign ap_sync_continue = ap_continue;

assign ap_sync_done = write_blocks_U0_ap_done;

assign ap_sync_krnl_idct_dataflow_entry6_U0_ap_ready = (krnl_idct_dataflow_entry6_U0_ap_ready | ap_sync_reg_krnl_idct_dataflow_entry6_U0_ap_ready);

assign ap_sync_read_blocks_ap_int_512_U0_ap_ready = (read_blocks_ap_int_512_U0_ap_ready | ap_sync_reg_read_blocks_ap_int_512_U0_ap_ready);

assign ap_sync_read_blocks_ap_uint_512_U0_ap_ready = (read_blocks_ap_uint_512_U0_ap_ready | ap_sync_reg_read_blocks_ap_uint_512_U0_ap_ready);

assign ap_sync_ready = (ap_sync_read_blocks_ap_uint_512_U0_ap_ready & ap_sync_read_blocks_ap_int_512_U0_ap_ready & ap_sync_krnl_idct_dataflow_entry6_U0_ap_ready);

assign execute_U0_ap_continue = 1'b1;

assign execute_U0_ap_start = icmp_ln331_loc_channel_empty_n;

assign execute_U0_ignore_dc = icmp_ln331_loc_channel_dout;

assign execute_U0_start_full_n = 1'b1;

assign execute_U0_start_write = 1'b0;

assign krnl_idct_dataflow_Block_split25_proc_U0_ap_continue = icmp_ln331_loc_channel_full_n;

assign krnl_idct_dataflow_Block_split25_proc_U0_ap_start = start_for_krnl_idct_dataflow_Block_split25_proc_U0_empty_n;

assign krnl_idct_dataflow_Block_split25_proc_U0_start_full_n = 1'b1;

assign krnl_idct_dataflow_Block_split25_proc_U0_start_write = 1'b0;

assign krnl_idct_dataflow_entry6_U0_ap_continue = 1'b1;

assign krnl_idct_dataflow_entry6_U0_ap_start = ((ap_sync_reg_krnl_idct_dataflow_entry6_U0_ap_ready ^ 1'b1) & ap_start);

assign krnl_idct_dataflow_entry6_U0_start_full_n = (start_for_write_blocks_U0_full_n & start_for_krnl_idct_dataflow_Block_split25_proc_U0_full_n);

assign m_axi_gmem0_ARADDR = read_blocks_ap_int_512_U0_m_axi_gmem0_ARADDR;

assign m_axi_gmem0_ARBURST = read_blocks_ap_int_512_U0_m_axi_gmem0_ARBURST;

assign m_axi_gmem0_ARCACHE = read_blocks_ap_int_512_U0_m_axi_gmem0_ARCACHE;

assign m_axi_gmem0_ARID = read_blocks_ap_int_512_U0_m_axi_gmem0_ARID;

assign m_axi_gmem0_ARLEN = read_blocks_ap_int_512_U0_m_axi_gmem0_ARLEN;

assign m_axi_gmem0_ARLOCK = read_blocks_ap_int_512_U0_m_axi_gmem0_ARLOCK;

assign m_axi_gmem0_ARPROT = read_blocks_ap_int_512_U0_m_axi_gmem0_ARPROT;

assign m_axi_gmem0_ARQOS = read_blocks_ap_int_512_U0_m_axi_gmem0_ARQOS;

assign m_axi_gmem0_ARREGION = read_blocks_ap_int_512_U0_m_axi_gmem0_ARREGION;

assign m_axi_gmem0_ARSIZE = read_blocks_ap_int_512_U0_m_axi_gmem0_ARSIZE;

assign m_axi_gmem0_ARUSER = read_blocks_ap_int_512_U0_m_axi_gmem0_ARUSER;

assign m_axi_gmem0_ARVALID = read_blocks_ap_int_512_U0_m_axi_gmem0_ARVALID;

assign m_axi_gmem0_AWADDR = 64'd0;

assign m_axi_gmem0_AWBURST = 2'd0;

assign m_axi_gmem0_AWCACHE = 4'd0;

assign m_axi_gmem0_AWID = 1'd0;

assign m_axi_gmem0_AWLEN = 32'd0;

assign m_axi_gmem0_AWLOCK = 2'd0;

assign m_axi_gmem0_AWPROT = 3'd0;

assign m_axi_gmem0_AWQOS = 4'd0;

assign m_axi_gmem0_AWREGION = 4'd0;

assign m_axi_gmem0_AWSIZE = 3'd0;

assign m_axi_gmem0_AWUSER = 1'd0;

assign m_axi_gmem0_AWVALID = 1'b0;

assign m_axi_gmem0_BREADY = 1'b0;

assign m_axi_gmem0_RREADY = read_blocks_ap_int_512_U0_m_axi_gmem0_RREADY;

assign m_axi_gmem0_WDATA = 512'd0;

assign m_axi_gmem0_WID = 1'd0;

assign m_axi_gmem0_WLAST = 1'b0;

assign m_axi_gmem0_WSTRB = 64'd0;

assign m_axi_gmem0_WUSER = 1'd0;

assign m_axi_gmem0_WVALID = 1'b0;

assign m_axi_gmem1_ARADDR = read_blocks_ap_uint_512_U0_m_axi_gmem1_ARADDR;

assign m_axi_gmem1_ARBURST = read_blocks_ap_uint_512_U0_m_axi_gmem1_ARBURST;

assign m_axi_gmem1_ARCACHE = read_blocks_ap_uint_512_U0_m_axi_gmem1_ARCACHE;

assign m_axi_gmem1_ARID = read_blocks_ap_uint_512_U0_m_axi_gmem1_ARID;

assign m_axi_gmem1_ARLEN = read_blocks_ap_uint_512_U0_m_axi_gmem1_ARLEN;

assign m_axi_gmem1_ARLOCK = read_blocks_ap_uint_512_U0_m_axi_gmem1_ARLOCK;

assign m_axi_gmem1_ARPROT = read_blocks_ap_uint_512_U0_m_axi_gmem1_ARPROT;

assign m_axi_gmem1_ARQOS = read_blocks_ap_uint_512_U0_m_axi_gmem1_ARQOS;

assign m_axi_gmem1_ARREGION = read_blocks_ap_uint_512_U0_m_axi_gmem1_ARREGION;

assign m_axi_gmem1_ARSIZE = read_blocks_ap_uint_512_U0_m_axi_gmem1_ARSIZE;

assign m_axi_gmem1_ARUSER = read_blocks_ap_uint_512_U0_m_axi_gmem1_ARUSER;

assign m_axi_gmem1_ARVALID = read_blocks_ap_uint_512_U0_m_axi_gmem1_ARVALID;

assign m_axi_gmem1_AWADDR = 64'd0;

assign m_axi_gmem1_AWBURST = 2'd0;

assign m_axi_gmem1_AWCACHE = 4'd0;

assign m_axi_gmem1_AWID = 1'd0;

assign m_axi_gmem1_AWLEN = 32'd0;

assign m_axi_gmem1_AWLOCK = 2'd0;

assign m_axi_gmem1_AWPROT = 3'd0;

assign m_axi_gmem1_AWQOS = 4'd0;

assign m_axi_gmem1_AWREGION = 4'd0;

assign m_axi_gmem1_AWSIZE = 3'd0;

assign m_axi_gmem1_AWUSER = 1'd0;

assign m_axi_gmem1_AWVALID = 1'b0;

assign m_axi_gmem1_BREADY = 1'b0;

assign m_axi_gmem1_RREADY = read_blocks_ap_uint_512_U0_m_axi_gmem1_RREADY;

assign m_axi_gmem1_WDATA = 512'd0;

assign m_axi_gmem1_WID = 1'd0;

assign m_axi_gmem1_WLAST = 1'b0;

assign m_axi_gmem1_WSTRB = 64'd0;

assign m_axi_gmem1_WUSER = 1'd0;

assign m_axi_gmem1_WVALID = 1'b0;

assign m_axi_gmem2_ARADDR = 64'd0;

assign m_axi_gmem2_ARBURST = 2'd0;

assign m_axi_gmem2_ARCACHE = 4'd0;

assign m_axi_gmem2_ARID = 1'd0;

assign m_axi_gmem2_ARLEN = 32'd0;

assign m_axi_gmem2_ARLOCK = 2'd0;

assign m_axi_gmem2_ARPROT = 3'd0;

assign m_axi_gmem2_ARQOS = 4'd0;

assign m_axi_gmem2_ARREGION = 4'd0;

assign m_axi_gmem2_ARSIZE = 3'd0;

assign m_axi_gmem2_ARUSER = 1'd0;

assign m_axi_gmem2_ARVALID = 1'b0;

assign m_axi_gmem2_AWADDR = write_blocks_U0_m_axi_gmem2_AWADDR;

assign m_axi_gmem2_AWBURST = write_blocks_U0_m_axi_gmem2_AWBURST;

assign m_axi_gmem2_AWCACHE = write_blocks_U0_m_axi_gmem2_AWCACHE;

assign m_axi_gmem2_AWID = write_blocks_U0_m_axi_gmem2_AWID;

assign m_axi_gmem2_AWLEN = write_blocks_U0_m_axi_gmem2_AWLEN;

assign m_axi_gmem2_AWLOCK = write_blocks_U0_m_axi_gmem2_AWLOCK;

assign m_axi_gmem2_AWPROT = write_blocks_U0_m_axi_gmem2_AWPROT;

assign m_axi_gmem2_AWQOS = write_blocks_U0_m_axi_gmem2_AWQOS;

assign m_axi_gmem2_AWREGION = write_blocks_U0_m_axi_gmem2_AWREGION;

assign m_axi_gmem2_AWSIZE = write_blocks_U0_m_axi_gmem2_AWSIZE;

assign m_axi_gmem2_AWUSER = write_blocks_U0_m_axi_gmem2_AWUSER;

assign m_axi_gmem2_AWVALID = write_blocks_U0_m_axi_gmem2_AWVALID;

assign m_axi_gmem2_BREADY = write_blocks_U0_m_axi_gmem2_BREADY;

assign m_axi_gmem2_RREADY = 1'b0;

assign m_axi_gmem2_WDATA = write_blocks_U0_m_axi_gmem2_WDATA;

assign m_axi_gmem2_WID = write_blocks_U0_m_axi_gmem2_WID;

assign m_axi_gmem2_WLAST = write_blocks_U0_m_axi_gmem2_WLAST;

assign m_axi_gmem2_WSTRB = write_blocks_U0_m_axi_gmem2_WSTRB;

assign m_axi_gmem2_WUSER = write_blocks_U0_m_axi_gmem2_WUSER;

assign m_axi_gmem2_WVALID = write_blocks_U0_m_axi_gmem2_WVALID;

assign read_blocks_ap_int_512_U0_ap_continue = 1'b1;

assign read_blocks_ap_int_512_U0_ap_start = ((ap_sync_reg_read_blocks_ap_int_512_U0_ap_ready ^ 1'b1) & ap_start);

assign read_blocks_ap_int_512_U0_start_full_n = 1'b1;

assign read_blocks_ap_int_512_U0_start_write = 1'b0;

assign read_blocks_ap_uint_512_U0_ap_continue = 1'b1;

assign read_blocks_ap_uint_512_U0_ap_start = ((ap_sync_reg_read_blocks_ap_uint_512_U0_ap_ready ^ 1'b1) & ap_start);

assign read_blocks_ap_uint_512_U0_start_full_n = 1'b1;

assign read_blocks_ap_uint_512_U0_start_write = 1'b0;

assign start_for_krnl_idct_dataflow_Block_split25_proc_U0_din = 1'b1;

assign start_for_write_blocks_U0_din = 1'b1;

assign write_blocks_U0_ap_continue = ap_continue;

assign write_blocks_U0_ap_start = start_for_write_blocks_U0_empty_n;

assign write_blocks_U0_start_full_n = 1'b1;

assign write_blocks_U0_start_write = 1'b0;

endmodule //krnl_idct_krnl_idct_dataflow
